-- Staging-only minimum schema for the Tenant Isolation Smoke workflow.
--
-- Run this in the SQL Editor of staging project ewappvtucmbmgptusvaq only.
-- It creates no users and copies no production data. The smoke workflow
-- creates disposable auth users/rows and removes them in a finally block.

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text not null,
  role text not null check (role in ('admin', 'parent', 'student', 'teacher')),
  parent_id uuid references public.profiles(id) on delete set null,
  family_id uuid,
  grade text,
  stream text,
  board text not null default 'CBSE',
  cbse_subjects jsonb not null default '[]'::jsonb,
  avatar text,
  account_status text not null default 'active',
  subscription_plan text not null default 'free',
  subscription_expires_at timestamptz,
  access_cbse boolean not null default true,
  daily_token_limit integer,
  monthly_token_limit integer,
  is_test_account boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_username_unique_ci
  on public.profiles (lower(trim(username)))
  where username is not null and trim(username) <> '';

create index if not exists profiles_parent_id_idx
  on public.profiles (parent_id);

create index if not exists profiles_family_id_idx
  on public.profiles (family_id);

create table if not exists public.student_progress (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  grade text not null,
  mode text not null,
  subject text not null,
  chapter text not null,
  current_step_index integer not null default 0,
  highest_unlocked_step integer not null default 0,
  completed boolean not null default false,
  last_lesson text,
  step_lessons jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, grade, mode, subject, chapter)
);

create index if not exists student_progress_profile_id_idx
  on public.student_progress (profile_id);

create table if not exists public.test_history (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  grade text not null,
  mode text not null,
  subject text not null,
  chapter text not null,
  exam_type text,
  difficulty text,
  percentage numeric,
  raw_score numeric,
  final_score numeric,
  max_score numeric,
  wrong_count integer not null default 0,
  penalty numeric not null default 0,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists test_history_profile_id_idx
  on public.test_history (profile_id);

create table if not exists public.teacher_student_assignments (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  grade text not null default 'Grade 9',
  subject text not null default '',
  section text not null default '',
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  unique (teacher_id, student_id, subject)
);

create index if not exists teacher_student_assignments_teacher_idx
  on public.teacher_student_assignments (teacher_id);

create index if not exists teacher_student_assignments_student_idx
  on public.teacher_student_assignments (student_id);

-- Direct client access is denied. The staging backend and smoke setup use the
-- service role, while authorization/tenant checks are exercised through the
-- deployed FastAPI endpoints.
alter table public.profiles enable row level security;
alter table public.student_progress enable row level security;
alter table public.test_history enable row level security;
alter table public.teacher_student_assignments enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.student_progress from anon, authenticated;
revoke all on table public.test_history from anon, authenticated;
revoke all on table public.teacher_student_assignments from anon, authenticated;

grant all on table public.profiles to service_role;
grant all on table public.student_progress to service_role;
grant all on table public.test_history to service_role;
grant all on table public.teacher_student_assignments to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;

notify pgrst, 'reload schema';

-- Expected result after running this script: four zero counts.
select
  (select count(*) from public.profiles) as profiles,
  (select count(*) from public.student_progress) as student_progress,
  (select count(*) from public.test_history) as test_history,
  (select count(*) from public.teacher_student_assignments) as teacher_student_assignments;
