import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";

import StructuredVisualBlock from "./StructuredVisualBlock";
import { normalizeTutorMarkdown } from "../utils/markdownCleanup";

// ── Feature flag — set to false to instantly roll back to accordion layout ───
// To roll back: change true → false, save, done. No other changes needed.
const USE_CARD_FEED_LAYOUT = true;

// ── Card Feed: section type detection ────────────────────────────────────────
// Colors use semi-transparent backgrounds + strong left-border accent so they
// look vivid in BOTH light mode and dark mode.
const CARD_TYPES = {
  intro:   { bg: "rgba(59,130,246,.07)",  border: "rgba(59,130,246,.35)",  accent: "#3b82f6", iconBg: "rgba(59,130,246,.15)",  icon: "🎯", label: "Introduction",  labelColor: "#3b82f6" },
  concept: { bg: "rgba(245,158,11,.07)",  border: "rgba(245,158,11,.35)",  accent: "#f59e0b", iconBg: "rgba(245,158,11,.15)",  icon: "📘", label: "Concept",       labelColor: "#d97706" },
  example: { bg: "rgba(34,197,94,.07)",   border: "rgba(34,197,94,.35)",   accent: "#22c55e", iconBg: "rgba(34,197,94,.15)",   icon: "🧪", label: "Examples",      labelColor: "#16a34a" },
  warning: { bg: "rgba(249,115,22,.07)",  border: "rgba(249,115,22,.35)",  accent: "#f97316", iconBg: "rgba(249,115,22,.15)",  icon: "⚠️", label: "Watch Out",     labelColor: "#ea580c" },
  check:   { bg: "rgba(239,68,68,.07)",   border: "rgba(239,68,68,.35)",   accent: "#ef4444", iconBg: "rgba(239,68,68,.15)",   icon: "✅", label: "Quick Check",   labelColor: "#dc2626" },
  summary: { bg: "rgba(139,92,246,.07)",  border: "rgba(139,92,246,.35)",  accent: "#8b5cf6", iconBg: "rgba(139,92,246,.15)",  icon: "📌", label: "Summary",       labelColor: "#7c3aed" },
  default: { bg: "rgba(107,114,128,.05)", border: "rgba(107,114,128,.25)", accent: "#6b7280", iconBg: "rgba(107,114,128,.1)",  icon: "📚", label: "Lesson",        labelColor: "#6b7280" },
};

function getSectionType(title) {
  const t = (title || "").toLowerCase();
  if (t.includes("what you will learn") || t.includes("introduction") || t.includes("overview") || t.includes("context") || t.includes("what we learn"))
    return "intro";
  if (t.includes("simple explanation") || t.includes("core explanation") || t.includes("concept") || t.includes("explanation") || t.includes("breakdown"))
    return "concept";
  if (t.includes("worked example") || t.includes("example") || t.includes("step-by-step") || t.includes("step by step"))
    return "example";
  if (t.includes("common mistake") || t.includes("warning") || t.includes("avoid") || t.includes("do not"))
    return "warning";
  if (t.includes("quick check") || t.includes("check question") || t.includes("practice") || t.includes("self check") || t.includes("question"))
    return "check";
  if (t.includes("summary") || t.includes("recap") || t.includes("revision") || t.includes("review") || t.includes("key points"))
    return "summary";
  return "default";
}

// ── Legacy icon map (used in accordion mode) ─────────────────────────────────
const SECTION_ICONS = {
  "What you will learn": "🎯",
  "Simple explanation": "📘",
  "Step-by-step breakdown": "🧩",
  "Worked example": "🧪",
  "Common mistake": "⚠️",
  "Quick check question": "✅",
  "Summary": "📌",
};

function cleanTitle(title) {
  return title.replace(/\*\*/g, "").replace(/#/g, "").trim();
}

function parseSections(markdown) {
  /**
   * Split lesson markdown into named sections.
   *
   * Handles four heading patterns generated by different LLMs / system prompts:
   *   1. Numbered+hash:  "## 1. What you will learn"   or  "1. What you will learn"
   *   2. Numbered+bold:  "**1. What You Will Learn**"
   *   3. Hash only:      "## What you will learn"       or  "# Overview"
   *   4. Bold only:      "**What you will learn**"      (standalone line)
   *
   * Patterns 3 and 4 were silently missed by the old regex (\d+\. required),
   * causing entire multi-section lessons to collapse into ONE card.
   */
  const lines = markdown.split("\n");
  const sections = [];
  let currentTitle = null;   // null = content before first heading (preamble)
  let currentContent = [];

  // Returns the captured title string if this line is a section heading, else null.
  function detectHeading(line) {
    // Pattern 1 & 2: numbered heading with optional # or ** wrapper
    //   "1. Title"  |  "## 1. Title"  |  "**1. Title**"  |  "## **1. Title**"
    // Guard: reject numbered LIST ITEMS (end with . or ?, or longer than 65 chars)
    //   "1. Read the sentence carefully..."  ← list item, NOT a heading
    //   "1. What you will learn"             ← heading ✅
    let m = line.match(/^#{0,3}\s*\**\s*(\d+\.\s+.+?)\**\s*$/);
    if (m) {
      const captured = m[1].replace(/^\d+\.\s*/, "").trim();
      // Real section headings: short, no terminal punctuation, title-like
      if (captured.length <= 65 && !/[.?!]$/.test(captured)) {
        return captured;
      }
    }

    // Pattern 3: markdown heading WITHOUT a number (## or ###)
    //   "## What you will learn"  |  "### Step-by-step breakdown"
    m = line.match(/^#{1,3}\s+(.+)$/);
    if (m) {
      const title = m[1].replace(/\*\*/g, "").trim();
      // Skip very short titles that are just decorative ("---" wrapped in ##)
      if (title.length >= 3) return title;
    }

    // Pattern 4: standalone bold line used as a heading
    //   "**What you will learn:**"  |  "**Summary**"
    // Must be the ENTIRE line (no surrounding prose), and long enough to be a heading.
    m = line.match(/^\*\*(.+?)\*\*:?\s*$/);
    if (m) {
      const title = m[1].trim();
      // Only treat as heading if it looks like a section title:
      // - doesn't start with a lowercase pronoun (avoids matching bold mid-sentence)
      // - length 4-80 chars
      if (title.length >= 4 && title.length <= 80 && !/^[a-z]/.test(title)) {
        return title;
      }
    }

    return null;
  }

  for (const line of lines) {
    const title = detectHeading(line);
    if (title) {
      if (currentContent.join("\n").trim()) {
        sections.push({
          title: cleanTitle(currentTitle || "Introduction"),
          content: currentContent.join("\n"),
        });
      }
      currentTitle = title;
      currentContent = [];
    } else {
      currentContent.push(line);
    }
  }

  if (currentContent.join("\n").trim()) {
    sections.push({
      title: cleanTitle(currentTitle || "Introduction"),
      content: currentContent.join("\n"),
    });
  }

  return sections;
}

function cleanQuestionText(text) {
  return text
    .replace(/```[\s\S]*?```/g, "")
    .replace(/!\[[^\]]*\]\([^)]*\)/g, "")
    .replace(/\[[^\]]*\]\([^)]*\)/g, "")
    .replace(/[#*_`>]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function getQuestionPrompt(section) {
  const title = section.title.toLowerCase();
  const content = cleanQuestionText(section.content);
  const invitationOnly =
    /would you like (that|to|me to)\??$/i.test(content) ||
    /^(if you want|would you like|do you want|shall we|we can now)\b/i.test(content);
  if (invitationOnly) return "";

  const isQuestionSection =
    title.includes("question") || title.includes("quick check") ||
    title.includes("self check") || title.includes("practice");

  const labelledQuestionMatch = content.match(
    /(?:^|\s)(?:question|quick check(?: question)?|try this|your turn)\s*:\s*([^]+?)(?=(?:\s(?:step\s*\d+|answer|hint|solution)\s*:)|$)/i
  );
  if (labelledQuestionMatch) {
    const prompt = labelledQuestionMatch[1].trim();
    if (/^would you like (that|to|me to)\??$/i.test(prompt)) return "";
    return prompt;
  }
  if (isQuestionSection) return content;

  const finalQuestionMatch = content.match(/([^.!?]*\?)\s*$/);
  if (finalQuestionMatch) {
    const prompt = finalQuestionMatch[1].trim();
    if (prompt.length >= 12 && !/^would you like (that|to|me to)\??$/i.test(prompt)) return prompt;
  }
  return "";
}

function getRenderableContent(section, questionPrompt) {
  if (!questionPrompt) return section.content;
  const title = section.title.toLowerCase();
  const withoutLabelledQuestion = section.content.replace(
    /(?:^|\n)\s*(?:[-*]\s*)?(?:\*\*)?(?:question|quick check(?: question)?|try this|your turn)(?:\*\*)?\s*:\s*[\s\S]*$/i,
    ""
  );
  if (withoutLabelledQuestion !== section.content) return withoutLabelledQuestion.trim();
  if (title.includes("question") || title.includes("quick check") || title.includes("self check") || title.includes("practice"))
    return "";
  const escapedPrompt = questionPrompt.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return section.content.replace(new RegExp(`${escapedPrompt}\\s*$`), "").trim();
}

function isHindiSubject(subject) {
  const s = (subject || "").toLowerCase();
  return s.includes("hindi") || s.includes("हिंदी") || s.includes("हिन्दी");
}

function formatMcqPrompt(prompt) {
  if (!prompt) return prompt;
  return prompt
    .replace(/\s+---+\s*$/, "")
    .replace(/\s+([a-dA-D]\))\s+/g, "\n$1 ")
    .replace(/^\s*([a-dA-D]\))\s+/g, "\n$1 ")
    .trim();
}

// ── Shared ReactMarkdown code renderer (used by both layouts) ─────────────────
function LessonMarkdownCode({ className, children, node }) {
  const language = className || "";
  const raw = String(children).replace(/\n$/, "");

  if (/language-visual-json/.test(language)) return <StructuredVisualBlock raw={raw} />;
  if (/language-mermaid/.test(language)) return null;

  const isLikelyLessonContent =
    !language &&
    node?.position?.start?.line !== undefined &&
    (raw.includes("* ") || raw.includes("- ") || raw.includes(". ") || raw.split("\n").length > 1);

  if (isLikelyLessonContent) {
    const blocks = [];
    let bulletBuffer = [];
    const flushBullets = () => {
      if (bulletBuffer.length > 0) {
        blocks.push(
          <ul key={`ul-${blocks.length}`} style={{ paddingLeft: "1.4em", margin: "0.5em 0" }}>
            {bulletBuffer.map((b, j) => <li key={j} style={{ marginBottom: "0.3em" }}>{b}</li>)}
          </ul>
        );
        bulletBuffer = [];
      }
    };
    raw.split("\n").forEach((line, i) => {
      const trimmed = line.trim();
      if (!trimmed) { flushBullets(); return; }
      if (trimmed.startsWith("* ") || trimmed.startsWith("- ")) {
        bulletBuffer.push(trimmed.slice(2));
      } else {
        flushBullets();
        blocks.push(<p key={`p-${i}`} style={{ margin: "0.4em 0" }}>{trimmed}</p>);
      }
    });
    flushBullets();
    return <div className="lesson-unwrapped-block">{blocks}</div>;
  }
  return <code className={className}>{children}</code>;
}

// ── Option A: single card in the scrollable feed ──────────────────────────────
function CardFeedSection({
  section,
  index,
  subject,
  questionModes,
  setQuestionModes,
  questionAnswers,
  setQuestionAnswers,
  questionFeedback,
  setQuestionFeedback,
  questionLoading,
  setQuestionLoading,
  onEvaluateQuestion,
}) {
  const type = getSectionType(section.title);
  const colours = CARD_TYPES[type];
  const questionPrompt = getQuestionPrompt(section);
  const renderableContent = getRenderableContent(section, questionPrompt);
  const questionMode = questionModes[index] || "";
  const answer = questionAnswers[index] || "";
  const feedback = questionFeedback[index] || "";
  const loading = questionLoading[index] || false;

  async function handleEvaluate() {
    if (!answer.trim() || !onEvaluateQuestion) return;
    setQuestionLoading((prev) => ({ ...prev, [index]: true }));
    setQuestionFeedback((prev) => ({ ...prev, [index]: "" }));
    try {
      const result = await onEvaluateQuestion({ question: questionPrompt, answer });
      setQuestionFeedback((prev) => ({
        ...prev,
        [index]: result?.evaluation || result?.message || "Your answer has been reviewed.",
      }));
    } catch {
      setQuestionFeedback((prev) => ({ ...prev, [index]: "Could not evaluate this answer right now." }));
    } finally {
      setQuestionLoading((prev) => ({ ...prev, [index]: false }));
    }
  }

  return (
    <div
      className={`lesson-card-feed-item lesson-card-type-${type}`}
      style={{
        borderRadius: 14,
        padding: "16px 18px",
        border: `1.5px solid ${colours.border}`,
        background: colours.bg,
        marginBottom: 14,
      }}
    >
      {/* Card header */}
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}>
        <span style={{
          width: 28, height: 28, borderRadius: 8,
          background: colours.iconBg,
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: ".9rem", flexShrink: 0,
        }}>
          {colours.icon}
        </span>
        <span style={{
          fontSize: ".62rem", fontWeight: 800, textTransform: "uppercase",
          letterSpacing: ".1em", color: colours.labelColor, marginRight: 4,
        }}>
          {colours.label}
        </span>
        <span style={{ fontSize: ".92rem", fontWeight: 700, lineHeight: 1.3 }}>
          <ReactMarkdown
            remarkPlugins={[remarkGfm, remarkMath]}
            rehypePlugins={[rehypeKatex]}
            components={{ p: ({ children }) => <>{children}</> }}
          >
            {`${index + 1}. ${section.title}`}
          </ReactMarkdown>
        </span>
      </div>

      {/* Card body — rendered markdown */}
      {renderableContent && (
        <div className="lesson-section-body lesson-card-body" style={{ fontSize: ".9rem", lineHeight: 1.7 }}>
          <ReactMarkdown
            remarkPlugins={[remarkGfm, remarkMath]}
            rehypePlugins={[rehypeKatex]}
            components={{ code: LessonMarkdownCode }}
          >
            {renderableContent}
          </ReactMarkdown>
        </div>
      )}

      {/* Inline question block — same logic as before */}
      {questionPrompt && (
        <div className="lesson-inline-question-box" style={{ marginTop: 14 }}>
          <div>
            <p className="lesson-inline-question-label">Want to try this question?</p>
            <div className="lesson-inline-question-text">
              <ReactMarkdown
                remarkPlugins={[remarkGfm, remarkMath]}
                rehypePlugins={[rehypeKatex]}
              >
                {formatMcqPrompt(questionPrompt)}
              </ReactMarkdown>
            </div>
          </div>

          <div className="lesson-inline-question-actions">
            {!isHindiSubject(subject) && (
              <button
                type="button"
                className={questionMode === "answer" ? "inline-question-choice active" : "inline-question-choice"}
                onClick={() => setQuestionModes((prev) => ({ ...prev, [index]: "answer" }))}
              >
                Answer and evaluate
              </button>
            )}
            <button
              type="button"
              className={
                questionMode === "think" || isHindiSubject(subject)
                  ? "inline-question-choice active muted"
                  : "inline-question-choice muted"
              }
              onClick={() => setQuestionModes((prev) => ({ ...prev, [index]: "think" }))}
            >
              Leave for thinking
            </button>
          </div>

          {questionMode === "think" && (
            <p className="lesson-inline-thinking-note">
              Saved as a thinking prompt. No answer will be checked.
            </p>
          )}

          {questionMode === "answer" && (
            <div className="lesson-inline-answer-panel">
              <textarea
                value={answer}
                onChange={(e) => setQuestionAnswers((prev) => ({ ...prev, [index]: e.target.value }))}
                placeholder="Write your answer here..."
                rows={4}
              />
              <button
                type="button"
                className="primary-btn lesson-inline-evaluate-btn"
                disabled={!answer.trim() || loading}
                onClick={handleEvaluate}
              >
                {loading ? "Evaluating..." : "Evaluate my answer"}
              </button>
              {feedback && (
                <div className="lesson-inline-feedback">
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm, remarkMath]}
                    rehypePlugins={[rehypeKatex]}
                  >
                    {feedback}
                  </ReactMarkdown>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ── Main export — switches between Card Feed (Option A) and legacy accordion ──
function LessonSections({ lesson, onEvaluateQuestion, subject, cardStyle = "default", cardTheme = "brand" }) {
  const sections = parseSections(normalizeTutorMarkdown(lesson));

  // Shared state for both layouts
  const [openSections, setOpenSections] = useState(sections.map((_, i) => i === 0));
  const [questionModes, setQuestionModes] = useState({});
  const [questionAnswers, setQuestionAnswers] = useState({});
  const [questionFeedback, setQuestionFeedback] = useState({});
  const [questionLoading, setQuestionLoading] = useState({});

  // ── Option A: Card Feed Layout ─────────────────────────────────────────────
  if (USE_CARD_FEED_LAYOUT) {
    return (
      <div className={`lesson-card-feed style-${cardStyle} theme-${cardTheme}`}>
        {sections.map((section, index) => (
          <CardFeedSection
            key={index}
            section={section}
            index={index}
            subject={subject}
            questionModes={questionModes}
            setQuestionModes={setQuestionModes}
            questionAnswers={questionAnswers}
            setQuestionAnswers={setQuestionAnswers}
            questionFeedback={questionFeedback}
            setQuestionFeedback={setQuestionFeedback}
            questionLoading={questionLoading}
            setQuestionLoading={setQuestionLoading}
            onEvaluateQuestion={onEvaluateQuestion}
          />
        ))}
      </div>
    );
  }

  // ── Legacy accordion layout (rollback path) ────────────────────────────────
  async function handleEvaluateQuestion(index, question) {
    const answer = questionAnswers[index] || "";
    if (!answer.trim() || !onEvaluateQuestion) return;
    setQuestionLoading((prev) => ({ ...prev, [index]: true }));
    setQuestionFeedback((prev) => ({ ...prev, [index]: "" }));
    try {
      const result = await onEvaluateQuestion({ question, answer });
      setQuestionFeedback((prev) => ({
        ...prev,
        [index]: result?.evaluation || result?.message || "Your answer has been reviewed.",
      }));
    } catch {
      setQuestionFeedback((prev) => ({ ...prev, [index]: "Could not evaluate this answer right now." }));
    } finally {
      setQuestionLoading((prev) => ({ ...prev, [index]: false }));
    }
  }

  return (
    <div className={`lesson-sections style-${cardStyle} theme-${cardTheme}`}>
      {sections.map((section, index) => {
        const questionPrompt = getQuestionPrompt(section);
        const renderableContent = getRenderableContent(section, questionPrompt);
        const questionMode = questionModes[index] || "";
        const answer = questionAnswers[index] || "";
        const feedback = questionFeedback[index] || "";
        const loading = questionLoading[index] || false;

        return (
          <div key={index} className={`lesson-section-card section-${index + 1}`} data-step={index + 1}>
            <button
              type="button"
              className="lesson-section-header"
              data-step={index + 1}
              onClick={() => setOpenSections((prev) => prev.map((item, i) => i === index ? !item : item))}
            >
              <div className="lesson-section-title">
                <span className="lesson-section-icon">{SECTION_ICONS[section.title] || "📚"}</span>
                <span>
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm, remarkMath]}
                    rehypePlugins={[rehypeKatex]}
                    components={{ p: ({ children }) => <>{children}</> }}
                  >
                    {`${index + 1}. ${section.title}`}
                  </ReactMarkdown>
                </span>
              </div>
              <span className="lesson-section-arrow">{openSections[index] ? "⌃" : "⌄"}</span>
            </button>

            {openSections[index] && (
              <div className="lesson-section-body">
                {renderableContent && (
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm, remarkMath]}
                    rehypePlugins={[rehypeKatex]}
                    components={{ code: LessonMarkdownCode }}
                  >
                    {renderableContent}
                  </ReactMarkdown>
                )}

                {questionPrompt && (
                  <div className="lesson-inline-question-box">
                    <div>
                      <p className="lesson-inline-question-label">Want to try this question?</p>
                      <div className="lesson-inline-question-text">
                        <ReactMarkdown remarkPlugins={[remarkGfm, remarkMath]} rehypePlugins={[rehypeKatex]}>
                          {formatMcqPrompt(questionPrompt)}
                        </ReactMarkdown>
                      </div>
                    </div>
                    <div className="lesson-inline-question-actions">
                      {!isHindiSubject(subject) && (
                        <button
                          type="button"
                          className={questionMode === "answer" ? "inline-question-choice active" : "inline-question-choice"}
                          onClick={() => setQuestionModes((prev) => ({ ...prev, [index]: "answer" }))}
                        >
                          Answer and evaluate
                        </button>
                      )}
                      <button
                        type="button"
                        className={questionMode === "think" || isHindiSubject(subject) ? "inline-question-choice active muted" : "inline-question-choice muted"}
                        onClick={() => setQuestionModes((prev) => ({ ...prev, [index]: "think" }))}
                      >
                        Leave for thinking
                      </button>
                    </div>
                    {questionMode === "think" && (
                      <p className="lesson-inline-thinking-note">Saved as a thinking prompt. No answer will be checked.</p>
                    )}
                    {questionMode === "answer" && (
                      <div className="lesson-inline-answer-panel">
                        <textarea
                          value={answer}
                          onChange={(e) => setQuestionAnswers((prev) => ({ ...prev, [index]: e.target.value }))}
                          placeholder="Write your answer here..."
                          rows={4}
                        />
                        <button
                          type="button"
                          className="primary-btn lesson-inline-evaluate-btn"
                          disabled={!answer.trim() || loading}
                          onClick={() => handleEvaluateQuestion(index, questionPrompt)}
                        >
                          {loading ? "Evaluating..." : "Evaluate my answer"}
                        </button>
                        {feedback && (
                          <div className="lesson-inline-feedback">
                            <ReactMarkdown remarkPlugins={[remarkGfm, remarkMath]} rehypePlugins={[rehypeKatex]}>
                              {feedback}
                            </ReactMarkdown>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default LessonSections;
