-- CBSE Board Sample Papers — Phase 1 (pilot)
-- Run once in the Supabase SQL Editor for BOTH projects:
--   1. Primary project      (Grade 5-10 content — run this for Grade 10 papers)
--   2. Grade 11/12 project  (run this too, even though the pilot is Grade 10 only,
--      so Grade 12 papers work later without a second migration pass)
--
-- board_sample_papers        — one row per (board, year, grade, subject) paper.
-- board_sample_paper_questions — one row per question within a paper.
--
-- Populate via:
--   python3 backend/scripts/extract_cbse_sample_paper.py   (paper + questions, no answers)
--   python3 backend/scripts/import_cbse_sample_paper_answers.py   (fills in answers)

CREATE TABLE IF NOT EXISTS board_sample_papers (
    id                     UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    board                  TEXT        NOT NULL DEFAULT 'CBSE',
    academic_year          TEXT        NOT NULL,
    grade                  TEXT        NOT NULL,
    subject                TEXT        NOT NULL,
    subject_variant        TEXT        DEFAULT '',
    source_subject_code    TEXT        NOT NULL,
    question_paper_url     TEXT        DEFAULT '',
    marking_scheme_url     TEXT        DEFAULT '',
    source_page_url        TEXT        DEFAULT '',
    status                 TEXT        DEFAULT 'active',
    created_at             TIMESTAMPTZ DEFAULT NOW(),
    updated_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_board_papers_unique
    ON board_sample_papers(board, academic_year, grade, source_subject_code);

CREATE INDEX IF NOT EXISTS idx_board_papers_lookup
    ON board_sample_papers(grade, academic_year DESC, subject);

ALTER TABLE board_sample_papers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "board sample papers are readable" ON board_sample_papers;
CREATE POLICY "board sample papers are readable"
    ON board_sample_papers FOR SELECT USING (true);

CREATE OR REPLACE FUNCTION set_board_sample_papers_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_board_sample_papers_updated_at ON board_sample_papers;
CREATE TRIGGER trg_board_sample_papers_updated_at
    BEFORE UPDATE ON board_sample_papers
    FOR EACH ROW EXECUTE FUNCTION set_board_sample_papers_updated_at();


CREATE TABLE IF NOT EXISTS board_sample_paper_questions (
    id                  UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    paper_id            UUID        NOT NULL REFERENCES board_sample_papers(id) ON DELETE CASCADE,
    question_number     TEXT        NOT NULL,
    section             TEXT        DEFAULT '',
    question_type       TEXT        DEFAULT 'short_answer',
    marks               INTEGER     DEFAULT 1,
    question_text       TEXT        NOT NULL,
    options             JSONB       DEFAULT '[]',
    diagram_dependent   BOOLEAN     DEFAULT FALSE,
    answer_text         TEXT        DEFAULT '',
    answer_explanation  TEXT        DEFAULT '',
    status              TEXT        DEFAULT 'extracted',
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_board_paper_questions_unique
    ON board_sample_paper_questions(paper_id, question_number);

CREATE INDEX IF NOT EXISTS idx_board_paper_questions_paper
    ON board_sample_paper_questions(paper_id);

ALTER TABLE board_sample_paper_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "board sample paper questions are readable" ON board_sample_paper_questions;
CREATE POLICY "board sample paper questions are readable"
    ON board_sample_paper_questions FOR SELECT USING (true);

CREATE OR REPLACE FUNCTION set_board_sample_paper_questions_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_board_sample_paper_questions_updated_at ON board_sample_paper_questions;
CREATE TRIGGER trg_board_sample_paper_questions_updated_at
    BEFORE UPDATE ON board_sample_paper_questions
    FOR EACH ROW EXECUTE FUNCTION set_board_sample_paper_questions_updated_at();

COMMENT ON TABLE board_sample_papers IS
    'Official CBSE sample question papers, one row per (board, year, grade, subject).
     PDFs are downloaded from cbseacademic.nic.in and re-hosted in Supabase Storage.
     status: pending_answers (extracted but not yet fully answered — hidden
     from student listings) | active (fully answered, visible to students) |
     missing_ms | missing_qp | archived.';

COMMENT ON TABLE board_sample_paper_questions IS
    'Individual questions parsed from a board_sample_papers question-paper PDF.
     Answers are filled in via a human-reviewed round trip (see
     backend/scripts/extract_cbse_sample_paper.py and import_cbse_sample_paper_answers.py)
     — never generated by a live LLM call at student-facing serve time.
     status: extracted (no answer yet) | answered (validated GPT-5 answer applied).';
