-- Doubt Knowledge Base (DKB)
-- ===========================
-- Internal Q&A cache for Ask Doubt.  Students are served answers from this
-- table instantly at zero AI token cost.  New answers generated by LLM are
-- automatically stored here for future reuse.  This mechanism is internal
-- and is never disclosed to students.
--
-- Run in Supabase SQL editor before starting the backend server.
-- Requires pgvector extension (already enabled for rag_chunks).

-- Ensure pgvector is enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Main Q&A knowledge base table
CREATE TABLE IF NOT EXISTS doubt_kb (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    grade           TEXT NOT NULL,
    board           TEXT NOT NULL DEFAULT 'CBSE',
    mode            TEXT NOT NULL DEFAULT 'CBSE',
    subject         TEXT NOT NULL,
    chapter         TEXT,
    question        TEXT NOT NULL,
    answer          TEXT NOT NULL,
    -- 1536-dimension vector from text-embedding-3-small
    -- same model as rag_chunks for consistency
    embedding       vector(1536),
    -- 'prewarmed' = admin pre-generated | 'llm' = auto-stored from LLM call
    source          TEXT NOT NULL DEFAULT 'llm',
    hit_count       INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_hit_at     TIMESTAMPTZ,
    status          TEXT NOT NULL DEFAULT 'active'  -- active | archived
);

-- Index for fast cosine similarity search
CREATE INDEX IF NOT EXISTS doubt_kb_embedding_idx
    ON doubt_kb USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- Index for filtering by grade/subject/chapter before vector search
CREATE INDEX IF NOT EXISTS doubt_kb_grade_subject_idx
    ON doubt_kb (grade, subject, chapter);

-- RPC function: semantic search within doubt_kb
-- Returns questions ordered by cosine similarity to the query embedding.
CREATE OR REPLACE FUNCTION match_doubt_kb(
    query_embedding vector(1536),
    match_count     INT DEFAULT 5,
    similarity_threshold FLOAT DEFAULT 0.80,
    filter_grade    TEXT DEFAULT NULL,
    filter_subject  TEXT DEFAULT NULL,
    filter_chapter  TEXT DEFAULT NULL,
    filter_mode     TEXT DEFAULT NULL
)
RETURNS TABLE (
    id          UUID,
    question    TEXT,
    answer      TEXT,
    subject     TEXT,
    chapter     TEXT,
    grade       TEXT,
    source      TEXT,
    hit_count   INTEGER,
    similarity  FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        dk.id,
        dk.question,
        dk.answer,
        dk.subject,
        dk.chapter,
        dk.grade,
        dk.source,
        dk.hit_count,
        1 - (dk.embedding <=> query_embedding) AS similarity
    FROM doubt_kb dk
    WHERE
        dk.status = 'active'
        AND (filter_grade   IS NULL OR dk.grade   = filter_grade)
        AND (filter_subject IS NULL OR dk.subject = filter_subject)
        AND (filter_chapter IS NULL OR dk.chapter = filter_chapter OR dk.chapter IS NULL)
        AND (filter_mode    IS NULL OR dk.mode    = filter_mode)
        AND 1 - (dk.embedding <=> query_embedding) >= similarity_threshold
    ORDER BY dk.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- RPC function: fetch pre-answered questions for a lesson chapter
-- Used to populate lesson follow-up suggestion cards.
CREATE OR REPLACE FUNCTION get_doubt_kb_suggestions(
    p_grade      TEXT,
    p_subject    TEXT,
    p_chapter    TEXT,
    p_mode       TEXT DEFAULT 'CBSE',
    p_limit      INT  DEFAULT 8
)
RETURNS TABLE (
    id        UUID,
    question  TEXT,
    hit_count INTEGER
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        dk.id,
        dk.question,
        dk.hit_count
    FROM doubt_kb dk
    WHERE
        dk.status   = 'active'
        AND dk.grade    = p_grade
        AND dk.subject  = p_subject
        AND dk.mode     = p_mode
        AND (dk.chapter = p_chapter OR dk.chapter IS NULL)
    ORDER BY dk.hit_count DESC, dk.created_at DESC
    LIMIT p_limit;
END;
$$;

-- Enable Row Level Security (admin-only writes, no direct student reads)
ALTER TABLE doubt_kb ENABLE ROW LEVEL SECURITY;

-- Service role has full access (backend uses service role key)
CREATE POLICY "service_role_full_access" ON doubt_kb
    FOR ALL TO service_role USING (true) WITH CHECK (true);
