"""
formula_import.py  —  POST /api/admin/formula-sheets/import
─────────────────────────────────────────────────────────────────────────────
Admin-only endpoint that bulk-upserts formula JSON generated by GPT into the
formula_sheets table.

Upsert key: (formula_name ILIKE + grade + subject + chapter)
  - Matching row → UPDATE
  - No match     → INSERT

Input body:
  {
    "grade": "Grade 9",
    "subject": "Mathematics",
    "formulas": [ { ...FormulaEntry... }, ... ]
  }

Response:
  { "success": true, "inserted": N, "updated": N, "skipped": N, "errors": [] }

Security:
  - require_admin enforced on every call
  - No secrets or PII exposed in response
  - Metadata is sanitised before logging
─────────────────────────────────────────────────────────────────────────────
"""
from __future__ import annotations

import logging
from typing import Any, List, Optional

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from app.services.auth_service import require_admin, admin_client

router = APIRouter()
_log = logging.getLogger("likhapoha.formula_import")

VALID_GRADES = {f"Grade {i}" for i in range(5, 13)}
VALID_DIFFICULTIES = {"easy", "medium", "hard"}
TABLE = "formula_sheets"


# ── Pydantic models ────────────────────────────────────────────────────────────

class FormulaEntry(BaseModel):
    formula_name: str
    expression: str
    chapter: str
    # Optional enrichment fields
    expression_latex: Optional[str] = None
    topic: Optional[str] = None
    chapter_order: Optional[int] = None
    display_order: Optional[int] = None
    difficulty: Optional[str] = None
    explanation: Optional[str] = None
    variables: Optional[str] = None
    example: Optional[str] = None
    solution_steps: Optional[str] = None
    memory_tip: Optional[str] = None
    tags: Optional[List[str]] = Field(default_factory=list)
    active: Optional[bool] = True


class FormulaImportRequest(BaseModel):
    grade: str
    subject: str
    formulas: List[FormulaEntry]


# ── Helper ────────────────────────────────────────────────────────────────────

def _safe_difficulty(d: Optional[str]) -> str:
    if d and d.lower() in VALID_DIFFICULTIES:
        return d.lower()
    return "medium"


# ── Endpoint ──────────────────────────────────────────────────────────────────

@router.post("/formula-sheets/import")
def import_formula_sheets(
    body: FormulaImportRequest,
    _admin=Depends(require_admin),
):
    """
    Bulk-upsert formula JSON into formula_sheets.
    Upsert key: formula_name (case-insensitive) + grade + subject + chapter.
    Returns counts of inserted, updated, skipped (unchanged), and any per-row errors.
    """
    # Validate grade
    if body.grade not in VALID_GRADES:
        return {
            "success": False,
            "message": f"Invalid grade '{body.grade}'. Must be one of: {sorted(VALID_GRADES)}",
        }

    if not body.subject or not body.subject.strip():
        return {"success": False, "message": "subject is required."}

    if not body.formulas:
        return {"success": False, "message": "formulas array is empty."}

    inserted = 0
    updated = 0
    skipped = 0
    errors: list[dict] = []

    for idx, entry in enumerate(body.formulas):
        try:
            formula_name = entry.formula_name.strip()
            chapter = entry.chapter.strip()

            if not formula_name or not entry.expression or not chapter:
                errors.append({"index": idx, "formula_name": formula_name,
                                "error": "Missing required field (formula_name, expression, or chapter)."})
                continue

            # Check for existing row — case-insensitive name match
            existing_resp = (
                admin_client.table(TABLE)
                .select("id")
                .ilike("formula_name", formula_name)
                .eq("grade", body.grade)
                .eq("subject", body.subject)
                .ilike("chapter", chapter)
                .execute()
            )
            existing_rows = existing_resp.data or []

            row: dict[str, Any] = {
                "formula_name":    formula_name,
                "expression":      entry.expression.strip(),
                "grade":           body.grade,
                "subject":         body.subject.strip(),
                "chapter":         chapter,
                "active":          True if entry.active is None else bool(entry.active),
                "difficulty":      _safe_difficulty(entry.difficulty),
            }

            # Optional fields — only set if present in the payload
            if entry.expression_latex:
                row["expression_latex"] = entry.expression_latex.strip()
            if entry.topic:
                row["topic"] = entry.topic.strip()
                row["section_title"] = entry.topic.strip()  # legacy column alias
            if entry.chapter_order is not None:
                row["chapter_order"] = entry.chapter_order
            if entry.display_order is not None:
                row["display_order"] = entry.display_order
            if entry.explanation:
                row["explanation"] = entry.explanation.strip()
            if entry.variables:
                row["variables"] = entry.variables.strip()
            if entry.example:
                row["example"] = entry.example.strip()
            if entry.solution_steps:
                row["solution_steps"] = entry.solution_steps.strip()
            if entry.memory_tip:
                row["memory_tip"] = entry.memory_tip.strip()
            if entry.tags:
                row["tags"] = [t.strip() for t in entry.tags if t.strip()]

            if existing_rows:
                # UPDATE — preserve existing id
                existing_id = existing_rows[0]["id"]
                admin_client.table(TABLE).update(row).eq("id", existing_id).execute()
                updated += 1
                _log.info("Updated formula '%s' (%s / %s / %s)",
                          formula_name, body.grade, body.subject, chapter)
            else:
                # INSERT
                admin_client.table(TABLE).insert(row).execute()
                inserted += 1
                _log.info("Inserted formula '%s' (%s / %s / %s)",
                          formula_name, body.grade, body.subject, chapter)

        except Exception as exc:  # pylint: disable=broad-except
            _log.error("Error importing formula at index %d: %s", idx, str(exc))
            errors.append({
                "index": idx,
                "formula_name": entry.formula_name if entry else f"index {idx}",
                "error": str(exc)[:200],
            })

    total = inserted + updated + skipped + len(errors)
    _log.info(
        "Formula import complete — grade=%s subject=%s total=%d inserted=%d updated=%d skipped=%d errors=%d",
        body.grade, body.subject, total, inserted, updated, skipped, len(errors)
    )

    return {
        "success": len(errors) == 0,
        "inserted": inserted,
        "updated": updated,
        "skipped": skipped,
        "errors": errors,
        "message": (
            f"Import complete: {inserted} inserted, {updated} updated, {skipped} skipped."
            if not errors else
            f"Import finished with {len(errors)} error(s). {inserted} inserted, {updated} updated."
        ),
    }
