import { useState, useRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { answerDoubt } from "../api/doubt";
import { hasPaidAccess } from "../utils/resolveSubscription";

/**
 * Strip LaTeX $...$ delimiters so math like $P(x)$, $(x-2)$ displays as plain text.
 * Also removes raw JSON blocks that the AI occasionally embeds in structured responses.
 */
function cleanMathText(text) {
  if (!text || typeof text !== "string") return text;

  // Remove raw JSON objects/arrays that appear in explanation text
  // (e.g. {"type":"flow","title":...} generated by tutor service structured visuals)
  let cleaned = text.replace(/\{[\s\S]*?"type"\s*:\s*"(flow|steps|cycle|compare|visual)"[\s\S]*?\}/g, "");

  // Strip LaTeX inline math delimiters $...$ → keep the inner expression
  // Handles: $P(x)$, $(x-2)$, $x^2$, $-6$, $y$ etc.
  cleaned = cleaned.replace(/\$([^$\n]+)\$/g, "$1");

  // Clean up any leftover stray $ signs
  cleaned = cleaned.replace(/\$/g, "");

  return cleaned.trim();
}

/**
 * Remove sentences/phrases that reference visuals (diagrams, figures, drawings)
 * since no images are rendered in the explanation panel.
 */
function removeVisualizationRefs(text) {
  if (!text || typeof text !== "string") return text;
  return text
    // Remove lines containing visualization/diagram language (heading or inline)
    .replace(/^.*(?:visual\s+instruction|let['']?s\s+visuali[sz]|as\s+shown\s+in\s+(?:the\s+)?(?:diagram|figure)|see\s+(?:the\s+)?(?:figure|diagram)|draw\s+a\s+diagram|refer\s+to\s+the\s+(?:diagram|figure|image)|in\s+the\s+(?:figure|diagram)\s+(?:above|below)|the\s+(?:diagram|figure)\s+(?:shows|illustrates)|visually?\s*:).*$/gim, "")
    // Remove any trailing empty bold headings like "**Something**\n" with no content after
    .replace(/\*\*[^*]+\*\*\s*\n\s*$/gm, "")
    .replace(/\n{3,}/g, "\n\n") // collapse multiple blank lines
    .trim();
}

const API_BASE = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

// ── NCERT Exemplar link (main browse page — more reliable than direct PDFs) ──
const EXEMPLAR_URL = "https://ncert.nic.in/exemplar-problems.php";
// Grade-specific hint text for the PDF button
const EXEMPLAR_HINTS = {
  "Grade 8":  "Class 8 Exemplar Books",
  "Grade 9":  "Class 9 Exemplar Books",
  "Grade 10": "Class 10 Exemplar Books",
  "Grade 11": "Class 11 Exemplar Books",
  "Grade 12": "Class 12 Exemplar Books",
};

// ── Curated topic cards — 12 per grade / subject (NCERT Exemplar focus) ──────
// `chapter` is the canonical NCERT chapter name used at RAG ingestion time
// (see backend/scripts/download_ncert_exemplar*.py) — sent as "Exemplar: {chapter}"
// so /api/doubt/answer's textbook-context retrieval hits the ingested Exemplar PDFs.
const TOPIC_CARDS = {
  "Grade 8": {
    Maths: [
      { topic: "Rational Numbers on Number Line", chapter: "Rational Numbers", difficulty: "Tricky", emoji: "🔢", hint: "Plotting fractions and decimals between integers" },
      { topic: "Squares and Square Roots", chapter: "Square-Square Root and Cube-Cube Root", difficulty: "Hard", emoji: "√", hint: "Long division method and patterns in perfect squares" },
      { topic: "Cubes and Cube Roots", chapter: "Square-Square Root and Cube-Cube Root", difficulty: "Hard", emoji: "³√", hint: "Prime factorisation and cube root tricks" },
      { topic: "Algebraic Expressions and Identities", chapter: "Algebraic Expressions and Identities", difficulty: "Tricky", emoji: "📐", hint: "(a+b)² = a²+2ab+b² and other key identities" },
      { topic: "Mensuration — Area and Volume", chapter: "Mensuration", difficulty: "Hard", emoji: "📦", hint: "Surface area of cubes, cuboids, and cylinders" },
      { topic: "Linear Equations in One Variable", chapter: "Linear Equation in One Variable", difficulty: "Tricky", emoji: "✏️", hint: "Word problems and transposing terms" },
      { topic: "Comparing Quantities — Percentage, Profit Loss", chapter: "Comparing Quantities", difficulty: "Tricky", emoji: "💹", hint: "Simple interest and compound interest" },
      { topic: "Data Handling — Bar Graphs and Probability", chapter: "Data Handling", difficulty: "Medium", emoji: "📊", hint: "Reading data and computing simple probability" },
      { topic: "Direct and Inverse Proportions", chapter: "Direct and Inverse Proportions", difficulty: "Tricky", emoji: "⚖️", hint: "Identify direct vs inverse, cross-multiplication shortcuts" },
      { topic: "Understanding Quadrilaterals", chapter: "Understanding Quadrilaterals and Practical Geometry", difficulty: "Hard", emoji: "◻️", hint: "Angle sum, properties of parallelogram, rhombus, trapezium" },
      { topic: "Playing with Numbers — Divisibility", chapter: "Playing with Numbers", difficulty: "Medium", emoji: "🎯", hint: "Divisibility rules for 2,3,4,5,6,9,11 and puzzles" },
      { topic: "Introduction to Graphs — Line and Bar", chapter: "Introduction to Graphs", difficulty: "Medium", emoji: "📉", hint: "Reading coordinates, plotting and interpreting bar/line graphs" },
    ],
    Science: [
      { topic: "Microorganisms — Friend and Foe", chapter: "Microorganisms: Friend and Foe", difficulty: "Tricky", emoji: "🦠", hint: "Bacteria, fungi, viruses and their roles" },
      { topic: "Cell — Structure and Functions", chapter: "Cell - Structure and Functions", difficulty: "Hard", emoji: "🔬", hint: "Animal vs plant cell, organelles and their functions" },
      { topic: "Conservation of Plants and Animals", chapter: "Conservation of Plants and Animals", difficulty: "Medium", emoji: "🌿", hint: "Biodiversity, endangered species, deforestation" },
      { topic: "Combustion and Flame", chapter: "Combustion and Flame", difficulty: "Tricky", emoji: "🔥", hint: "Types of combustion, fire triangle, fire extinguishers" },
      { topic: "Force and Pressure", chapter: "Force and Pressure", difficulty: "Hard", emoji: "⚡", hint: "Contact vs non-contact forces, atmospheric pressure" },
      { topic: "Sound — Nature and Propagation", chapter: "Sound", difficulty: "Tricky", emoji: "🔊", hint: "Frequency, amplitude, audible range and vibrations" },
      { topic: "Light — Reflection and Refraction", chapter: "Light", difficulty: "Hard", emoji: "💡", hint: "Laws of reflection, types of mirrors and lenses" },
      { topic: "Pollution of Air and Water", chapter: "Pollution of Air and Water", difficulty: "Medium", emoji: "🌫️", hint: "Causes, effects and measures to control pollution" },
      { topic: "Reproduction in Animals", chapter: "Reproduction in Animals", difficulty: "Medium", emoji: "🐣", hint: "Sexual vs asexual reproduction, human reproduction basics" },
      { topic: "Metals and Non-Metals", chapter: "Materials: Metals and Non-Metals", difficulty: "Tricky", emoji: "⚙️", hint: "Physical and chemical properties, uses, reactions with acids" },
      { topic: "Friction — Types and Effects", chapter: "Friction", difficulty: "Tricky", emoji: "🛝", hint: "Static, sliding, rolling friction; ways to increase/decrease" },
      { topic: "Stars and the Solar System", chapter: "Stars and the Solar System", difficulty: "Medium", emoji: "⭐", hint: "Planets, stars, constellations, moon phases, satellites" },
    ],
  },
  "Grade 9": {
    Maths: [
      { topic: "Number System — Irrational Numbers", chapter: "Number Systems", difficulty: "Hard", emoji: "π", hint: "Representation on number line, rationalising denominators" },
      { topic: "Polynomials — Remainder & Factor Theorem", chapter: "Polynomials", difficulty: "Hard", emoji: "📈", hint: "p(x) at x=a, factorising using the factor theorem" },
      { topic: "Coordinate Geometry — Plotting Points", chapter: "Coordinate Geometry", difficulty: "Medium", emoji: "📍", hint: "Quadrants, x and y axis, plotting (x,y)" },
      { topic: "Lines and Angles — Parallel Lines", chapter: "Lines and Angles", difficulty: "Tricky", emoji: "∠", hint: "Alternate angles, co-interior angles, transversal proofs" },
      { topic: "Triangles — Congruence Rules", chapter: "Triangles", difficulty: "Hard", emoji: "△", hint: "SSS, SAS, ASA, AAS, RHS congruence conditions" },
      { topic: "Surface Area and Volume of Solids", chapter: "Surface Areas and Volumes", difficulty: "Hard", emoji: "📦", hint: "Cone, cylinder, sphere — curved surface vs total surface" },
      { topic: "Statistics — Mean, Median, Mode", chapter: "Statistics", difficulty: "Tricky", emoji: "📊", hint: "Grouped data, frequency tables, bar vs histogram" },
      { topic: "Probability — Basic Concepts", chapter: "Probability", difficulty: "Medium", emoji: "🎲", hint: "Sample space, events, P(E) = n(E)/n(S)" },
      { topic: "Quadrilaterals — Properties and Proofs", chapter: "Quadrilaterals", difficulty: "Hard", emoji: "◻️", hint: "Mid-point theorem, properties of parallelogram, proving quadrilateral types" },
      { topic: "Circles — Arcs, Chords and Angles", chapter: "Circles", difficulty: "Hard", emoji: "⭕", hint: "Equal chords, angles subtended at centre vs circumference" },
      { topic: "Heron's Formula — Area of Triangle", chapter: "Heron's Formula", difficulty: "Tricky", emoji: "△", hint: "s = (a+b+c)/2, A = √[s(s-a)(s-b)(s-c)]" },
      { topic: "Constructions — Bisectors and Triangles", chapter: "Constructions", difficulty: "Medium", emoji: "📏", hint: "Perpendicular bisector, angle bisector, triangle constructions" },
    ],
    Science: [
      { topic: "Matter in Our Surroundings — States of Matter", chapter: "Matter in Our Surroundings", difficulty: "Tricky", emoji: "🌊", hint: "Evaporation, sublimation, latent heat and inter-conversion" },
      { topic: "Structure of the Atom — Models", chapter: "Structure of the Atom", difficulty: "Hard", emoji: "⚛️", hint: "Thomson, Rutherford, Bohr models — electrons and nucleus" },
      { topic: "Force and Laws of Motion", chapter: "Force and Laws of Motion", difficulty: "Hard", emoji: "🏎️", hint: "Newton's 3 laws, inertia, F=ma, action-reaction pairs" },
      { topic: "Gravitation — Universal Law", chapter: "Gravitation", difficulty: "Hard", emoji: "🌍", hint: "g = GM/R², weight vs mass, free fall" },
      { topic: "Work, Energy and Power", chapter: "Work and Energy", difficulty: "Tricky", emoji: "⚡", hint: "W=Fs·cosθ, KE = ½mv², conservation of energy" },
      { topic: "Sound — Wave Properties", chapter: "Sound", difficulty: "Tricky", emoji: "🔊", hint: "Speed, frequency, wavelength, echo, ultrasound" },
      { topic: "Tissues — Plant and Animal", chapter: "Tissues", difficulty: "Hard", emoji: "🔬", hint: "Meristematic vs permanent, types of animal tissues" },
      { topic: "Natural Resources — Atmosphere and Water", chapter: "Natural Resources", difficulty: "Medium", emoji: "🌎", hint: "Nitrogen cycle, water cycle, air composition" },
      { topic: "Motion — Distance, Speed, Velocity", chapter: "Motion", difficulty: "Hard", emoji: "🚀", hint: "Scalar vs vector, v=u+at, s=ut+½at², v²=u²+2as" },
      { topic: "Diversity in Living Organisms", chapter: "Diversity in Living Organisms", difficulty: "Tricky", emoji: "🦋", hint: "Kingdoms, classification criteria, Whittaker's 5-kingdom system" },
      { topic: "Why Do We Fall Ill — Health and Disease", chapter: "Why Do We Fall Ill", difficulty: "Medium", emoji: "🏥", hint: "Infectious vs non-infectious, immune system, prevention" },
      { topic: "Improvement in Food Resources", chapter: "Improvement in Food Resources", difficulty: "Medium", emoji: "🌾", hint: "Crop production, manures, irrigation, animal husbandry" },
    ],
  },
  "Grade 10": {
    Maths: [
      { topic: "Real Numbers — Euclid's Algorithm & HCF", chapter: "Real Numbers", difficulty: "Hard", emoji: "🔢", hint: "Division algorithm, HCF via Euclid, prime factorisation" },
      { topic: "Polynomials — Relationship of Zeroes", chapter: "Polynomials", difficulty: "Hard", emoji: "📉", hint: "Sum and product of zeroes, quadratic and cubic polynomials" },
      { topic: "Quadratic Equations — Discriminant", chapter: "Quadratic Equations", difficulty: "Hard", emoji: "🔺", hint: "D>0 two roots, D=0 equal roots, D<0 no real roots" },
      { topic: "Arithmetic Progressions — nth Term", chapter: "Arithmetic Progressions", difficulty: "Tricky", emoji: "🔁", hint: "a_n = a+(n-1)d, sum S_n = n/2(2a+(n-1)d)" },
      { topic: "Triangles — Similarity and Pythagoras", chapter: "Triangles", difficulty: "Hard", emoji: "△", hint: "BPT theorem, AA, SAS, SSS similarity criteria" },
      { topic: "Coordinate Geometry — Section Formula", chapter: "Coordinate Geometry", difficulty: "Tricky", emoji: "📍", hint: "Distance, section, midpoint formulas and area of triangle" },
      { topic: "Introduction to Trigonometry", chapter: "Introduction to Trigonometry and Its Applications", difficulty: "Hard", emoji: "📐", hint: "sin²θ+cos²θ=1, ratios in right triangles, values at 30/45/60°" },
      { topic: "Areas Related to Circles", chapter: "Areas Related to Circles", difficulty: "Tricky", emoji: "⭕", hint: "Sector area, arc length, segment area — mixed problems" },
      { topic: "Surface Areas and Volumes — Combined Solids", chapter: "Surface Areas and Volumes", difficulty: "Hard", emoji: "📦", hint: "Cone on cylinder, hemisphere on sphere — combined SA and volume" },
      { topic: "Statistics — Grouped Data, Median, Mode", chapter: "Statistics", difficulty: "Tricky", emoji: "📊", hint: "Median from cumulative frequency, mode from frequency table" },
      { topic: "Probability — Playing Cards and Dice", chapter: "Probability", difficulty: "Medium", emoji: "🎲", hint: "Deck of 52 cards, two-dice problems, compound events" },
      { topic: "Constructions — Tangents and Similar Triangles", chapter: "Constructions", difficulty: "Tricky", emoji: "📏", hint: "Tangent from external point, triangle construction with ratio" },
    ],
    Science: [
      { topic: "Chemical Reactions and Equations", chapter: "Chemical Reactions and Equations", difficulty: "Hard", emoji: "⚗️", hint: "Balancing equations, types of reactions — combination, displacement" },
      { topic: "Acids, Bases and Salts", chapter: "Acids, Bases and Salts", difficulty: "Tricky", emoji: "🧪", hint: "pH scale, neutralisation, common salts and their uses" },
      { topic: "Life Processes — Nutrition and Respiration", chapter: "Life Processes", difficulty: "Hard", emoji: "🌱", hint: "Autotrophic vs heterotrophic, aerobic vs anaerobic respiration" },
      { topic: "Electricity — Ohm's Law and Circuits", chapter: "Electricity", difficulty: "Hard", emoji: "🔌", hint: "V=IR, series and parallel circuits, power P=VI" },
      { topic: "Magnetic Effects of Current", chapter: "Magnetic Effects of Electric Current", difficulty: "Hard", emoji: "🧲", hint: "Right-hand thumb rule, motor effect, electromagnetic induction" },
      { topic: "Refraction of Light — Lenses", chapter: "Light - Reflection and Refraction", difficulty: "Hard", emoji: "🔭", hint: "Lens formula 1/v−1/u=1/f, magnification, power of lens" },
      { topic: "Heredity and Evolution — Mendel's Laws", chapter: "Heredity and Evolution", difficulty: "Tricky", emoji: "🧬", hint: "Dominant/recessive traits, Punnett square, natural selection" },
      { topic: "Our Environment — Food Chains", chapter: "Our Environment", difficulty: "Medium", emoji: "🌿", hint: "Trophic levels, biomagnification, ozone depletion" },
      { topic: "Carbon and Its Compounds", chapter: "Carbon and Its Compounds", difficulty: "Hard", emoji: "⚛️", hint: "Covalent bonding, functional groups, homologous series, reactions" },
      { topic: "Control and Coordination — Nervous System", chapter: "Control and Coordination", difficulty: "Tricky", emoji: "🧠", hint: "Reflex arc, brain parts, hormones and their functions" },
      { topic: "Light — Reflection and Spherical Mirrors", chapter: "Light - Reflection and Refraction", difficulty: "Hard", emoji: "💡", hint: "Mirror formula, sign convention, ray diagrams for concave/convex" },
      { topic: "Sources of Energy — Conventional and New", chapter: "Sources of Energy", difficulty: "Medium", emoji: "☀️", hint: "Fossil fuels, solar, wind, nuclear — advantages and limitations" },
    ],
  },
  "Grade 11": {
    Physics: [
      { topic: "Units & Measurement — Dimensional Analysis", chapter: "Units and Measurements", difficulty: "Hard", emoji: "📏", hint: "Derive formulae using dimensions, check homogeneity, SI prefixes" },
      { topic: "Motion in a Straight Line — Kinematics", chapter: "Motion in a Straight Line", difficulty: "Hard", emoji: "🚀", hint: "v=u+at, s=ut+½at², v²=u²+2as, sign convention for direction" },
      { topic: "Motion in a Plane — Projectile Motion", chapter: "Motion in a Plane", difficulty: "Hard", emoji: "🎯", hint: "Horizontal range R=u²sin2θ/g, max height, time of flight" },
      { topic: "Laws of Motion — Newton & Friction", chapter: "Laws of Motion", difficulty: "Hard", emoji: "⚖️", hint: "F=ma, pseudo forces, static vs kinetic friction, inclined planes" },
      { topic: "Work, Energy and Power — Conservation", chapter: "Work, Energy and Power", difficulty: "Hard", emoji: "⚡", hint: "W=Fs·cosθ, KE=½mv², elastic vs inelastic collisions" },
      { topic: "Rotational Motion — Moment of Inertia", chapter: "System of Particles and Rotational Motion", difficulty: "Hard", emoji: "🔄", hint: "τ=Iα, angular momentum L=Iω, theorems of MI" },
      { topic: "Gravitation — Kepler's Laws", chapter: "Gravitation", difficulty: "Hard", emoji: "🌍", hint: "T²∝r³, escape velocity, orbital velocity, gravitational PE" },
      { topic: "Mechanical Properties of Solids", chapter: "Mechanical Properties of Solids", difficulty: "Tricky", emoji: "🔩", hint: "Stress, strain, Young's modulus, Hooke's law, elastic limit" },
      { topic: "Fluid Mechanics — Bernoulli's Theorem", chapter: "Mechanical Properties of Fluids", difficulty: "Hard", emoji: "💧", hint: "P+½ρv²+ρgh=constant, surface tension, viscosity, Stokes' law" },
      { topic: "Thermal Properties — Expansion & Calorimetry", chapter: "Thermal Properties of Matter", difficulty: "Tricky", emoji: "🌡️", hint: "Linear, area, volume expansion; specific heat; Newton's law of cooling" },
      { topic: "Thermodynamics — Laws and Processes", chapter: "Thermodynamics", difficulty: "Hard", emoji: "🔥", hint: "1st law ΔU=Q-W; isothermal/adiabatic/isobaric processes; Carnot efficiency" },
      { topic: "Kinetic Theory of Gases — RMS Speed", chapter: "Kinetic Theory", difficulty: "Hard", emoji: "🔬", hint: "PV=nRT, vrms=sqrt(3RT/M), degrees of freedom, equipartition theorem" },
    ],
    Chemistry: [
      { topic: "Some Basic Concepts — Mole and Stoichiometry", chapter: "Some Basic Concepts of Chemistry", difficulty: "Hard", emoji: "⚗️", hint: "Mole concept, limiting reagent, % yield, empirical vs molecular formula" },
      { topic: "Structure of Atom — Quantum Numbers", chapter: "Structure of Atom", difficulty: "Hard", emoji: "⚛️", hint: "n,l,m,s quantum numbers, Pauli exclusion, Hund's rule, aufbau principle" },
      { topic: "Periodic Table — Periodic Trends", chapter: "Classification of Elements and Periodicity in Properties", difficulty: "Tricky", emoji: "📋", hint: "IE, EA, electronegativity, atomic radius trends across periods and groups" },
      { topic: "Chemical Bonding — VSEPR and Hybridisation", chapter: "Chemical Bonding and Molecular Structure", difficulty: "Hard", emoji: "🔗", hint: "sp, sp2, sp3 hybridisation; VSEPR shapes; bond angle vs lone pairs" },
      { topic: "States of Matter — Kinetic Theory of Gases", chapter: "States of Matter", difficulty: "Tricky", emoji: "💨", hint: "Ideal gas equation, van der Waals, real vs ideal gas deviations" },
      { topic: "Thermodynamics — Hess's Law", chapter: "Thermodynamics", difficulty: "Hard", emoji: "🌡️", hint: "ΔH, ΔS, ΔG = ΔH-TΔS; spontaneity; Born-Haber cycle" },
      { topic: "Equilibrium — Kp, Kc and Le Chatelier", chapter: "Equilibrium", difficulty: "Hard", emoji: "⚖️", hint: "Kc=[products]/[reactants], Kp=Kc(RT)^Dn, buffer solutions, pH" },
      { topic: "Redox Reactions — Oxidation Number", chapter: "Redox Reactions", difficulty: "Tricky", emoji: "🔋", hint: "Assign oxidation number, balance by ON method, electrode notation" },
      { topic: "s-Block Elements — Anomalous Properties", chapter: "The s-Block Elements", difficulty: "Tricky", emoji: "🧲", hint: "Li and Be diagonal relationship, flame test, Na2O2 reactions" },
      { topic: "p-Block Elements — Group 13 & 14", chapter: "The p-Block Elements", difficulty: "Hard", emoji: "🧪", hint: "Boron chemistry, inert pair effect, allotropy of carbon, silicones" },
      { topic: "Organic Chemistry — IUPAC Nomenclature", chapter: "Organic Chemistry: Some Basic Principles and Techniques", difficulty: "Hard", emoji: "⛓️", hint: "Priority rules, E/Z isomerism, functional group nomenclature order" },
      { topic: "Hydrocarbons — Alkanes, Alkenes, Alkynes", chapter: "Hydrocarbons", difficulty: "Hard", emoji: "⛽", hint: "FR substitution in alkanes, electrophilic addition, Markovnikov's rule" },
    ],
    Biology: [
      { topic: "Living World — Classification Criteria", chapter: "The Living World", difficulty: "Tricky", emoji: "🌍", hint: "Biodiversity, nomenclature, ICBN rules, binomial nomenclature" },
      { topic: "Biological Classification — 5 Kingdoms", chapter: "Biological Classification", difficulty: "Hard", emoji: "🦠", hint: "Monera, Protista, Fungi, Plantae, Animalia — Whittaker's criteria" },
      { topic: "Plant Kingdom — Alternation of Generations", chapter: "Plant Kingdom", difficulty: "Hard", emoji: "🌿", hint: "Algae, bryophytes, pteridophytes, gymnosperms, angiosperms" },
      { topic: "Animal Kingdom — Basis of Classification", chapter: "Animal Kingdom", difficulty: "Hard", emoji: "🐠", hint: "Levels of organization, symmetry, coelom, segmentation, notochord" },
      { topic: "Cell — Structure and Ultra-structure", chapter: "Cell: The Unit of Life", difficulty: "Hard", emoji: "🔬", hint: "Prokaryote vs eukaryote, cell organelles, membrane structure (fluid mosaic)" },
      { topic: "Cell Division — Mitosis and Meiosis", chapter: "Cell Cycle and Cell Division", difficulty: "Hard", emoji: "🧬", hint: "Phases of mitosis/meiosis, crossing over, significance, karyokinesis vs cytokinesis" },
      { topic: "Transport in Plants — Osmosis and Imbibition", chapter: "Transport in Plants", difficulty: "Tricky", emoji: "💧", hint: "Water potential, plasmolysis, transpiration pull, ascent of sap" },
      { topic: "Mineral Nutrition — Essential Elements", chapter: "Mineral Nutrition", difficulty: "Tricky", emoji: "🌱", hint: "Macro vs micro nutrients, deficiency symptoms, nitrogen fixation" },
      { topic: "Photosynthesis — Light and Dark Reactions", chapter: "Photosynthesis in Higher Plants", difficulty: "Hard", emoji: "☀️", hint: "PS I & II, Calvin cycle, C3 vs C4 plants, photorespiration" },
      { topic: "Respiration — Glycolysis and Krebs Cycle", chapter: "Respiration in Plants", difficulty: "Hard", emoji: "🫁", hint: "ATP yield, ETS, oxidative phosphorylation, RQ of fats vs carbs" },
      { topic: "Plant Growth and Development — Phytohormones", chapter: "Plant Growth and Development", difficulty: "Tricky", emoji: "🌸", hint: "Auxin, gibberellin, cytokinin, abscisic acid, ethylene functions" },
      { topic: "Morphology of Flowering Plants", chapter: "Morphology of Flowering Plants", difficulty: "Tricky", emoji: "🌼", hint: "Root, stem, leaf modifications; inflorescence types; floral formula" },
    ],
    Maths: [
      { topic: "Sets — Operations and De Morgan's Laws", chapter: "Sets", difficulty: "Tricky", emoji: "⊂", hint: "Union, intersection, complement; De Morgan's; Venn diagram problems" },
      { topic: "Relations and Functions — Types", chapter: "Relations and Functions", difficulty: "Hard", emoji: "→", hint: "One-one, onto, bijective; inverse function; composition of functions" },
      { topic: "Trigonometric Functions — Identities", chapter: "Trigonometric Functions", difficulty: "Hard", emoji: "📐", hint: "Addition, double angle, half angle formulae; solving equations in [0,2pi]" },
      { topic: "Principle of Mathematical Induction", chapter: "Principle of Mathematical Induction", difficulty: "Tricky", emoji: "🔢", hint: "P(1) true, assume P(k), prove P(k+1) — divisibility and sum problems" },
      { topic: "Complex Numbers — Modulus-Argument Form", chapter: "Complex Numbers and Quadratic Equations", difficulty: "Hard", emoji: "i", hint: "z=a+ib, |z|, arg(z), cube roots of unity, De Moivre's theorem" },
      { topic: "Linear Inequalities — Graphical Method", chapter: "Linear Inequalities", difficulty: "Tricky", emoji: "≤", hint: "Shading feasible region, intersection of half-planes, system of inequalities" },
      { topic: "Permutations and Combinations", chapter: "Permutations and Combinations", difficulty: "Hard", emoji: "🔀", hint: "nPr, nCr, circular permutations, identical objects, distinct cases" },
      { topic: "Binomial Theorem — General Term", chapter: "Binomial Theorem", difficulty: "Hard", emoji: "∑", hint: "T(r+1) = nCr * x^(n-r) * a^r, middle term, coefficient problems" },
      { topic: "Sequences and Series — AP and GP", chapter: "Sequences and Series", difficulty: "Hard", emoji: "➕", hint: "nth term, sum, AM-GM inequality, sum of infinite GP" },
      { topic: "Straight Lines — Slope and Equations", chapter: "Straight Lines", difficulty: "Hard", emoji: "📏", hint: "Angle between lines, distance from a point, family of lines" },
      { topic: "Conic Sections — Parabola, Ellipse, Hyperbola", chapter: "Conic Sections", difficulty: "Hard", emoji: "⭕", hint: "Standard forms, focus-directrix, eccentricity, chord of contact" },
      { topic: "Introduction to 3D Geometry", chapter: "Introduction to Three Dimensional Geometry", difficulty: "Tricky", emoji: "📦", hint: "Distance formula, section formula in 3D, locus problems" },
    ],
  },
  "Grade 12": {
    Physics: [
      { topic: "Electrostatics — Gauss's Law", chapter: "Electric Charges and Fields", difficulty: "Hard", emoji: "⚡", hint: "Flux = q/e0; field due to sheet, sphere, wire; potential energy" },
      { topic: "Current Electricity — Kirchhoff's Laws", chapter: "Current Electricity", difficulty: "Hard", emoji: "🔌", hint: "KVL, KCL, Wheatstone bridge, meter bridge, potentiometer" },
      { topic: "Moving Charges — Biot-Savart Law", chapter: "Moving Charges and Magnetism", difficulty: "Hard", emoji: "🧲", hint: "Field due to circular loop, solenoid, toroid; cyclotron; force between wires" },
      { topic: "Magnetism — Diamagnetic, Paramagnetic", chapter: "Magnetism and Matter", difficulty: "Tricky", emoji: "🔮", hint: "Hysteresis, B-H curve, magnetic susceptibility, Earth's magnetism" },
      { topic: "Electromagnetic Induction — Faraday's Laws", chapter: "Electromagnetic Induction", difficulty: "Hard", emoji: "🔄", hint: "EMF = -dΦ/dt, Lenz's law, mutual inductance, AC generator" },
      { topic: "Alternating Current — Resonance", chapter: "Alternating Current", difficulty: "Hard", emoji: "〰️", hint: "Impedance, phase diagrams, power factor, Q-factor of LC circuit" },
      { topic: "Electromagnetic Waves — Spectrum", chapter: "Electromagnetic Waves", difficulty: "Tricky", emoji: "📡", hint: "E and B oscillations, c=1/sqrt(mu0*e0), wavelength ranges of EM spectrum" },
      { topic: "Ray Optics — Lens Maker's Equation", chapter: "Ray Optics and Optical Instruments", difficulty: "Hard", emoji: "🔭", hint: "1/f=(n-1)(1/R1-1/R2), dispersion, total internal reflection, optical fibre" },
      { topic: "Wave Optics — Young's Double Slit", chapter: "Wave Optics", difficulty: "Hard", emoji: "🌈", hint: "Fringe width = lambdaD/d, resolving power, polarisation by Malus's law" },
      { topic: "Dual Nature — Photoelectric Effect", chapter: "Dual Nature of Radiation and Matter", difficulty: "Hard", emoji: "☀️", hint: "hv = phi + KE_max, stopping potential, de Broglie wavelength = h/mv" },
      { topic: "Nuclei — Radioactive Decay Laws", chapter: "Nuclei", difficulty: "Hard", emoji: "☢️", hint: "N=N0*e^(-lambdat), half-life = 0.693/lambda, Q-value of reactions" },
      { topic: "Semiconductor Devices — PN Junction", chapter: "Semiconductor Electronics: Materials, Devices and Simple Circuits", difficulty: "Hard", emoji: "💡", hint: "Depletion layer, forward/reverse bias, Zener diode, transistor, logic gates" },
    ],
    Chemistry: [
      { topic: "Solutions — Colligative Properties", chapter: "Solutions", difficulty: "Hard", emoji: "🧪", hint: "Raoult's law, elevation of boiling point, depression of freezing point; van't Hoff factor" },
      { topic: "Electrochemistry — Nernst Equation", chapter: "Electrochemistry", difficulty: "Hard", emoji: "🔋", hint: "E=E0-(RT/nF)lnQ, standard electrode potential, electrolysis calculations" },
      { topic: "Chemical Kinetics — Order and Rate Laws", chapter: "Chemical Kinetics", difficulty: "Hard", emoji: "⏱️", hint: "Rate=k[A]^m[B]^n; integrated rate laws; Arrhenius equation; half-life" },
      { topic: "Surface Chemistry — Adsorption & Catalysis", chapter: "Surface Chemistry", difficulty: "Tricky", emoji: "🔬", hint: "Physisorption vs chemisorption, Freundlich isotherm, enzyme catalysis" },
      { topic: "d and f Block Elements — Transition Metals", chapter: "The d and f Block Elements", difficulty: "Hard", emoji: "⚙️", hint: "Variable oxidation states, magnetic properties, colour, catalytic activity" },
      { topic: "Coordination Compounds — IUPAC and VBT", chapter: "Coordination Compounds", difficulty: "Hard", emoji: "🔗", hint: "Nomenclature, isomerism, coordination number, EAN rule, CFT basics" },
      { topic: "Haloalkanes and Haloarenes — SN1 vs SN2", chapter: "Haloalkanes and Haloarenes", difficulty: "Hard", emoji: "⛓️", hint: "SN1 vs SN2 mechanism, E1/E2 elimination, nucleophilic aromatic substitution" },
      { topic: "Alcohols, Phenols and Ethers", chapter: "Alcohols, Phenols and Ethers", difficulty: "Hard", emoji: "🍾", hint: "Acidic strength order, Lucas test, Williamson ether synthesis, reactions" },
      { topic: "Aldehydes and Ketones — Nucleophilic Addition", chapter: "Aldehydes, Ketones and Carboxylic Acids", difficulty: "Hard", emoji: "🧫", hint: "Addition of HCN, Grignard; Aldol condensation; Cannizzaro; Tollen's test" },
      { topic: "Carboxylic Acids and Derivatives", chapter: "Aldehydes, Ketones and Carboxylic Acids", difficulty: "Hard", emoji: "🍋", hint: "Acidity order, decarboxylation, esterification, reactions with PCl5" },
      { topic: "Amines — Basicity and Reactions", chapter: "Amines", difficulty: "Hard", emoji: "🔵", hint: "Basicity order, Gabriel synthesis, diazotisation, coupling reactions" },
      { topic: "Biomolecules — Carbohydrates and Proteins", chapter: "Biomolecules", difficulty: "Tricky", emoji: "🧬", hint: "Reducing sugars, peptide bonds, denaturation, enzyme action" },
    ],
    Biology: [
      { topic: "Reproduction in Organisms", chapter: "Reproduction in Organisms", difficulty: "Tricky", emoji: "🌸", hint: "Asexual vs sexual, vegetative propagation, sporulation, budding" },
      { topic: "Human Reproduction — Gametogenesis", chapter: "Human Reproduction", difficulty: "Hard", emoji: "🧬", hint: "Spermatogenesis, oogenesis, menstrual cycle, fertilisation, implantation" },
      { topic: "Reproductive Health — Contraception", chapter: "Reproductive Health", difficulty: "Medium", emoji: "🏥", hint: "Types of contraception, STIs, MTP, infertility causes and ART" },
      { topic: "Principles of Inheritance — Mendel's Laws", chapter: "Principles of Inheritance and Variation", difficulty: "Hard", emoji: "🔬", hint: "Law of segregation, independent assortment, Punnett square, chi-square" },
      { topic: "Molecular Basis of Inheritance — DNA", chapter: "Molecular Basis of Inheritance", difficulty: "Hard", emoji: "🧪", hint: "DNA replication, transcription, translation, genetic code, mutations" },
      { topic: "Evolution — Darwinism and Speciation", chapter: "Evolution", difficulty: "Tricky", emoji: "🦕", hint: "Natural selection, Hardy-Weinberg, adaptive radiation, speciation mechanisms" },
      { topic: "Human Health and Disease — Immunity", chapter: "Human Health and Disease", difficulty: "Hard", emoji: "🛡️", hint: "Innate vs acquired immunity, antibody structure, vaccines, cancer, AIDS" },
      { topic: "Microbes in Human Welfare", chapter: "Microbes in Human Welfare", difficulty: "Tricky", emoji: "🦠", hint: "Biogas, antibiotics, sewage treatment, bioactive molecules" },
      { topic: "Biotechnology — Principles and Processes", chapter: "Biotechnology: Principles and Processes", difficulty: "Hard", emoji: "⚗️", hint: "Recombinant DNA, restriction enzymes, PCR, gel electrophoresis, cloning" },
      { topic: "Biotechnology and its Applications", chapter: "Biotechnology and Its Applications", difficulty: "Hard", emoji: "🌾", hint: "Bt cotton, golden rice, insulin production, gene therapy, bioethics" },
      { topic: "Ecosystem — Productivity and Energy Flow", chapter: "Ecosystem", difficulty: "Hard", emoji: "🌿", hint: "GPP/NPP, ecological pyramids, nutrient cycling, succession, decomposition" },
      { topic: "Biodiversity and Conservation", chapter: "Biodiversity and Conservation", difficulty: "Tricky", emoji: "🐘", hint: "In-situ vs ex-situ conservation, IUCN categories, hotspots, threats" },
    ],
    Maths: [
      { topic: "Relations and Functions — Inverse and Composition", chapter: "Relations and Functions", difficulty: "Hard", emoji: "→", hint: "Bijective for inverse, f∘g vs g∘f, binary operations, identity element" },
      { topic: "Inverse Trigonometric Functions", chapter: "Inverse Trigonometric Functions", difficulty: "Hard", emoji: "📐", hint: "Principal value, domain/range, properties and identities" },
      { topic: "Matrices and Determinants", chapter: "Matrices", difficulty: "Hard", emoji: "▣", hint: "Row operations, adjoint, inverse matrix, Cramer's rule, properties of determinants" },
      { topic: "Continuity and Differentiability", chapter: "Continuity and Differentiability", difficulty: "Hard", emoji: "📈", hint: "Continuity at a point, chain rule, implicit diff, parametric diff, Rolle's theorem" },
      { topic: "Applications of Derivatives", chapter: "Application of Derivatives", difficulty: "Hard", emoji: "📉", hint: "Increasing/decreasing, maxima/minima, tangent/normal, rate of change" },
      { topic: "Integrals — Integration Techniques", chapter: "Integrals", difficulty: "Hard", emoji: "∫", hint: "Substitution, by parts, partial fractions, special integrals" },
      { topic: "Applications of Integrals — Area", chapter: "Application of Integrals", difficulty: "Hard", emoji: "⭕", hint: "Area between curves, area of circle/ellipse using integration" },
      { topic: "Differential Equations", chapter: "Differential Equations", difficulty: "Hard", emoji: "dy/dx", hint: "Variable separable, homogeneous, linear DE, integrating factor" },
      { topic: "Vector Algebra — Dot and Cross Product", chapter: "Vector Algebra", difficulty: "Hard", emoji: "→", hint: "Magnitude, direction cosines, projection, scalar triple product" },
      { topic: "Three Dimensional Geometry", chapter: "Three Dimensional Geometry", difficulty: "Hard", emoji: "📦", hint: "Direction cosines, equation of line/plane, angle between lines, distance" },
      { topic: "Linear Programming — Corner Point Method", chapter: "Linear Programming", difficulty: "Tricky", emoji: "⚖️", hint: "Feasible region, objective function, graphical solution, optimal values" },
      { topic: "Probability — Bayes Theorem and Distributions", chapter: "Probability", difficulty: "Hard", emoji: "🎲", hint: "Conditional probability, Bayes theorem, Bernoulli trials, binomial distribution" },
    ],
  },
};

const DIFFICULTY_COLORS = {
  Hard:   { bg: "rgba(239,68,68,.1)",   border: "rgba(239,68,68,.3)",   text: "#ef4444",  label: "🔴 Hard" },
  Tricky: { bg: "rgba(245,158,11,.1)", border: "rgba(245,158,11,.3)", text: "#f59e0b", label: "🟡 Tricky" },
  Medium: { bg: "rgba(59,130,246,.1)",  border: "rgba(59,130,246,.3)",  text: "#3b82f6",  label: "🔵 Medium" },
};

const SUBJECT_COLORS = {
  Maths:     { icon: "📐", gradient: "linear-gradient(135deg,#2563eb,#7c3aed)", tag: "Mathematics" },
  Science:   { icon: "🔬", gradient: "linear-gradient(135deg,#059669,#0891b2)", tag: "Science" },
  Physics:   { icon: "⚛️", gradient: "linear-gradient(135deg,#6366f1,#8b5cf6)", tag: "Physics" },
  Chemistry: { icon: "🧪", gradient: "linear-gradient(135deg,#0891b2,#059669)", tag: "Chemistry" },
  Biology:   { icon: "🌿", gradient: "linear-gradient(135deg,#16a34a,#0891b2)", tag: "Biology" },
};

/** Return subjects available for a grade, filtered by stream for Grade 11/12 */
function getSubjectsForGrade(grade, user) {
  if (grade === "Grade 11" || grade === "Grade 12") {
    const stream = (user?.stream || "").toUpperCase();
    const all = ["Physics", "Chemistry", "Maths", "Biology"];
    if (stream === "PCM")  return ["Physics", "Chemistry", "Maths"];
    if (stream === "PCB")  return ["Physics", "Chemistry", "Biology"];
    if (stream === "PCMB") return ["Physics", "Chemistry", "Maths", "Biology"];
    // Admin / teacher / unknown stream — show all
    return all;
  }
  return ["Maths", "Science"];
}

/** The Grade 11/12 Exemplar RAG chapters were ingested under subject "Mathematics",
 * not "Maths" (see backend/scripts/upload_ncert_exemplar_grade1112_rag.py
 * FOLDER_TO_SUBJECT), while every other grade/subject uses "Maths". Translate only
 * for the API subject param so /api/doubt/answer's RAG filter actually matches —
 * the UI tab/label keeps using "Maths" everywhere. */
function toRagSubject(grade, subject) {
  if ((grade === "Grade 11" || grade === "Grade 12") && subject === "Maths") return "Mathematics";
  return subject;
}

/** Friendly upgrade prompt shown when a free/promo user clicks a topic card */
function UpgradeCard({ onClose, onUpgrade }) {
  return (
    <div style={{ textAlign: "center", padding: "20px 16px" }}>
      <div style={{ fontSize: "2.4rem", marginBottom: 10 }}>🔐</div>
      <h4 style={{ margin: "0 0 8px", fontSize: "1rem" }}>This feature is for paid subscribers</h4>
      <p style={{ fontSize: ".82rem", color: "var(--muted)", lineHeight: 1.6, marginBottom: 16 }}>
        AI-powered topic explanations, formula breakdowns, and exam tips are available with a paid plan.
        <br />Your current plan does not include this feature.
      </p>
      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        <button onClick={onUpgrade}
          style={{ padding: "10px 20px", borderRadius: 9, border: "none", background: "linear-gradient(135deg,#6366f1,#8b5cf6)", color: "#fff", fontWeight: 700, fontSize: ".88rem", cursor: "pointer", fontFamily: "inherit" }}>
          🚀 See Plans & Upgrade
        </button>
        <button onClick={onClose}
          style={{ padding: "8px 16px", borderRadius: 9, border: "1px solid var(--border)", background: "transparent", color: "var(--muted)", fontSize: ".8rem", cursor: "pointer", fontFamily: "inherit" }}>
          Maybe later
        </button>
      </div>
    </div>
  );
}

export default function ExemplarResearchPage({ user, setActivePage }) {
  const isTeacher = user?.role === "teacher";
  const userGrade = user?.grade || "Grade 9";
  const paidAccess = hasPaidAccess(user);

  // Grade selector — teachers can view any grade; students see only their own
  const [selectedGrade, setSelectedGrade] = useState(isTeacher ? "Grade 10" : userGrade);
  const isUpperSecondary = (g => g === "Grade 11" || g === "Grade 12")(isTeacher ? "Grade 10" : userGrade);
  const [selectedSubject, setSelectedSubject] = useState(isUpperSecondary ? "Physics" : "Maths");
  const [activeTopic, setActiveTopic] = useState(null);
  const [explanation, setExplanation] = useState("");
  const [loading, setLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResult, setSearchResult] = useState("");
  const [searchLoading, setSearchLoading] = useState(false);
  const [filterDifficulty, setFilterDifficulty] = useState("All");

  // ── Client-side explanation cache: grade|subject|topic → text ────────────
  // Prevents duplicate LLM calls for topics already fetched in this session.
  const explanationCache = useRef({});

  const cards = TOPIC_CARDS[selectedGrade]?.[selectedSubject] || [];
  const filteredCards = filterDifficulty === "All"
    ? cards
    : cards.filter(c => c.difficulty === filterDifficulty);

  async function explainTopic(topic, forceRefresh = false) {
    setActiveTopic(topic);
    setPracticeQs([]);
    setPracticeAnswers({});
    setPracticeRevealed({});
    if (!paidAccess) { setExplanation(""); return; }

    // ── Cache hit: serve instantly without LLM call ───────────────────────
    const cacheKey = `${selectedGrade}|${selectedSubject}|${topic.topic}`;
    if (!forceRefresh && explanationCache.current[cacheKey]) {
      setExplanation(explanationCache.current[cacheKey]);
      return;
    }

    setExplanation("");
    setLoading(true);
    try {
      // Pre-authored via GPT-5.5 handover, served instantly — no live LLM
      // call. See docs/EXEMPLAR_RESEARCH_CONTENT_STATUS.md for why this
      // replaced the old live /api/doubt/answer call.
      const res = await fetch(`${API_BASE}/api/teacher/exemplar-research/explain`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${user?.accessToken}`,
        },
        body: JSON.stringify({
          grade: selectedGrade,
          subject: selectedSubject,
          chapter: topic.chapter,
          topic: topic.topic,
        }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        setExplanation(data.message || data.detail?.message || "Could not load explanation. Please try again.");
        return;
      }
      // Post-process: remove any visualization references (kept for parity with
      // the old live-answer path; pre-authored content shouldn't contain these).
      const cleaned = removeVisualizationRefs(cleanMathText(data.explanation) || "Could not load explanation.");
      explanationCache.current[cacheKey] = cleaned;
      setExplanation(cleaned);
    } catch {
      setExplanation("Could not load explanation. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleSearch(e) {
    e?.preventDefault();
    if (!searchQuery.trim()) return;
    if (!paidAccess) {
      setSearchResult("__upgrade__");
      return;
    }
    setSearchResult("");
    setSearchLoading(true);
    try {
      const res = await fetch(`${API_BASE}/api/doubt/answer`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${user?.accessToken}`,
        },
        body: JSON.stringify({
          username: user?.username,
          grade: selectedGrade,
          mode: "CBSE",
          board: "CBSE",
          subject: toRagSubject(selectedGrade, selectedSubject),
          chapter: searchQuery,
          question: `Explain "${searchQuery}" for a CBSE ${selectedGrade} ${selectedSubject} student in detail. Include definition, key concept, example, and what to watch out for in exams.`,
          save_to_history: false,
        }),
      });
      const data = await res.json();
      setSearchResult(data.answer || "No explanation found.");
    } catch {
      setSearchResult("Search failed. Please try again.");
    } finally {
      setSearchLoading(false);
    }
  }

  const exemplarHint = EXEMPLAR_HINTS[selectedGrade] || "NCERT Exemplar Books";

  // ── Inline practice questions state ──────────────────────────────────────
  const [practiceQs, setPracticeQs] = useState([]);
  const [practiceLoading, setPracticeLoading] = useState(false);
  const [practiceAnswers, setPracticeAnswers] = useState({});
  const [practiceRevealed, setPracticeRevealed] = useState({});

  async function generatePractice(topic) {
    if (!paidAccess) { setActiveTopic(topic); return; }
    setPracticeQs([]);
    setPracticeAnswers({});
    setPracticeRevealed({});
    setPracticeLoading(true);

    /** Helper: call the doubt API and return the answer text */
    async function callDoubt(questionText) {
      const r = await fetch(`${API_BASE}/api/doubt/answer`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${user?.accessToken}` },
        body: JSON.stringify({
          username: user?.username,
          grade: selectedGrade,
          mode: "CBSE",
          board: "CBSE",
          subject: toRagSubject(selectedGrade, selectedSubject),
          chapter: `Exemplar: ${topic.chapter}`,
          question: questionText,
          save_to_history: false,
        }),
      });
      const d = await r.json();
      return (d.answer || "").trim();
    }

    try {
      // ── Pass 1: generate questions ────────────────────────────────────────
      const raw = await callDoubt(
        `Generate exactly 4 NCERT Exemplar-level MCQ practice questions on "${topic.topic}" for CBSE ${selectedGrade} ${selectedSubject}. Each must be a tricky/HOTS question.

IMPORTANT RULES:
- Do NOT use LaTeX, dollar signs, or math notation. Write all math in plain text (e.g. x^2, P(x), (x-2)(x-3)).
- You MUST include a detailed explanation of at least 3 sentences for EVERY question. NEVER leave explanation blank or short.
- The explanation must show the complete step-by-step working to reach the correct answer.

Respond ONLY with a valid JSON array (no markdown):
[{"q":"...","options":["A) ...","B) ...","C) ...","D) ..."],"answer":"A) ...","explanation":"Step 1: ... Step 2: ... Therefore the answer is A because ..."}]`
      );
      const start = raw.indexOf("["), end = raw.lastIndexOf("]");
      if (start === -1 || end === -1) { setPracticeQs([]); return; }

      let parsed;
      try { parsed = JSON.parse(raw.slice(start, end + 1)); } catch { setPracticeQs([]); return; }

      // Clean LaTeX from all fields
      let cleanedQs = parsed.map(q => ({
        ...q,
        q: cleanMathText(q.q),
        options: q.options ? q.options.map(o => cleanMathText(o)) : q.options,
        answer: cleanMathText(q.answer),
        explanation: q.explanation ? cleanMathText(q.explanation) : "",
      }));

      // ── Pass 2: if any explanation is missing or too short, fetch all explanations ─
      const needsExplanations = cleanedQs.some(q => !q.explanation || q.explanation.length < 40);
      if (needsExplanations) {
        const questionsText = cleanedQs
          .map((q, i) => `Q${i+1}: ${q.q}\nCorrect answer: ${q.answer}`)
          .join("\n\n");

        const explRaw = await callDoubt(
          `For each of these ${selectedSubject} questions about "${topic.topic}" (Grade ${selectedGrade}), provide a detailed explanation of at least 3 sentences showing the complete working.

${questionsText}

Do NOT use dollar signs or LaTeX. Write all math in plain text.
Respond ONLY with a JSON array of exactly ${cleanedQs.length} explanation strings:
["Full explanation for Q1 showing step by step working...", "Full explanation for Q2...", ...]`
        );
        const es = explRaw.indexOf("["), ee = explRaw.lastIndexOf("]");
        if (es !== -1 && ee !== -1) {
          try {
            const explanations = JSON.parse(explRaw.slice(es, ee + 1));
            cleanedQs = cleanedQs.map((q, i) => ({
              ...q,
              explanation: (explanations[i] && typeof explanations[i] === "string")
                ? cleanMathText(explanations[i])
                : q.explanation,
            }));
          } catch { /* keep existing explanations */ }
        }
      }

      setPracticeQs(cleanedQs);
    } catch { setPracticeQs([]); }
    finally { setPracticeLoading(false); }
  }

  return (
    <div className="premium-page" style={{ maxWidth: 1100 }}>

      {/* ── Controls row ── */}
      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center", marginBottom: 20 }}>

        {/* Grade picker — teachers see all, students see their own only */}
        {isTeacher ? (
          <select value={selectedGrade} onChange={e => { const g = e.target.value; setSelectedGrade(g); setActiveTopic(null); setExplanation(""); setSelectedSubject((g === "Grade 11" || g === "Grade 12") ? "Physics" : "Maths"); }}
            style={{ padding: "8px 12px", borderRadius: 8, border: "1.5px solid var(--border)", background: "var(--card-bg)", color: "var(--text)", fontFamily: "inherit", fontSize: ".85rem" }}>
            {["Grade 8","Grade 9","Grade 10","Grade 11","Grade 12"].map(g => <option key={g}>{g}</option>)}
          </select>
        ) : (
          <span style={{ padding: "8px 14px", borderRadius: 8, background: "rgba(99,102,241,.1)", border: "1px solid rgba(99,102,241,.3)", color: "#a5b4fc", fontSize: ".85rem", fontWeight: 700 }}>
            📚 {selectedGrade}
          </span>
        )}

        {/* Subject tabs — Grade 11/12 show Physics/Chemistry/Bio/Maths filtered by stream */}
        {getSubjectsForGrade(selectedGrade, user).map(subj => (
          <button key={subj} onClick={() => { setSelectedSubject(subj); setActiveTopic(null); setExplanation(""); setFilterDifficulty("All"); }}
            style={{ padding: "8px 18px", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", fontSize: ".85rem", fontWeight: 700,
              background: selectedSubject === subj ? (SUBJECT_COLORS[subj]?.gradient || "linear-gradient(135deg,#6366f1,#8b5cf6)") : "var(--card-bg)",
              color: selectedSubject === subj ? "#fff" : "var(--muted)",
              border: selectedSubject === subj ? "none" : "1.5px solid var(--border)",
            }}>
            {SUBJECT_COLORS[subj]?.icon || "📚"} {subj}
          </button>
        ))}

        {/* Difficulty filter */}
        <select value={filterDifficulty} onChange={e => setFilterDifficulty(e.target.value)}
          style={{ padding: "8px 12px", borderRadius: 8, border: "1.5px solid var(--border)", background: "var(--card-bg)", color: "var(--text)", fontFamily: "inherit", fontSize: ".85rem" }}>
          <option value="All">All Difficulty</option>
          <option value="Hard">🔴 Hard Only</option>
          <option value="Tricky">🟡 Tricky Only</option>
          <option value="Medium">🔵 Medium Only</option>
        </select>

        {/* Exemplar link — main NCERT browse page (reliable) */}
        <a href={EXEMPLAR_URL} target="_blank" rel="noreferrer"
          style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "8px 14px", borderRadius: 8,
            background: "rgba(16,185,129,.1)", border: "1px solid rgba(16,185,129,.3)",
            color: "#10b981", fontWeight: 700, fontSize: ".82rem", textDecoration: "none" }}>
          📄 Browse {exemplarHint}
        </a>
      </div>

      {/* ── Search bar ── */}
      <form onSubmit={handleSearch} style={{ display: "flex", gap: 10, marginBottom: 24 }}>
        <input
          placeholder={`Search any ${selectedSubject} topic… e.g. "Ohm's Law" or "Quadratic Formula"`}
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          style={{ flex: 1, padding: "11px 16px", borderRadius: 10, border: "1.5px solid var(--border)", background: "var(--card-bg)", color: "var(--text)", fontFamily: "inherit", fontSize: ".9rem", outline: "none" }}
        />
        <button type="submit" className="primary-btn" disabled={searchLoading || !searchQuery.trim()} style={{ maxWidth: 180 }}>
          {searchLoading ? "Searching…" : "🔍 Explain This"}
        </button>
      </form>

      {/* Search result (or upgrade gate) */}
      {searchResult && searchResult !== "__upgrade__" && (
        <div className="premium-card" style={{ marginBottom: 24, borderLeft: "4px solid #6366f1" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
            <h4 style={{ margin: 0, color: "#6366f1" }}>🔍 Research Result: {searchQuery}</h4>
            <button onClick={() => { setSearchResult(""); setSearchQuery(""); }}
              style={{ background: "none", border: "none", cursor: "pointer", color: "var(--muted)", fontSize: "1.1rem" }}>×</button>
          </div>
          <div className="markdown-content" style={{ fontSize: ".88rem" }}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{searchResult}</ReactMarkdown>
          </div>
        </div>
      )}
      {searchResult === "__upgrade__" && (
        <UpgradeCard onClose={() => { setSearchResult(""); }} onUpgrade={() => setActivePage?.("subscriptionPlans")} />
      )}

      {/* ── Main layout: cards + explanation panel — flex-wrap for mobile ── */}
      <div className="exemplar-layout">

        {/* Topic cards grid */}
        <div className="exemplar-card-panel">
          <p style={{ fontSize: ".75rem", fontWeight: 700, color: "var(--muted)", marginBottom: 12, textTransform: "uppercase", letterSpacing: ".08em" }}>
            {filteredCards.length} topics · click any card to get instant AI explanation
          </p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 14 }}>
            {filteredCards.map((card, i) => {
              const dc = DIFFICULTY_COLORS[card.difficulty] || DIFFICULTY_COLORS.Medium;
              const isActive = activeTopic?.topic === card.topic;
              return (
                <button key={i} onClick={() => explainTopic(card)}
                  style={{
                    display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 8,
                    padding: "16px 18px", borderRadius: 14, cursor: "pointer", textAlign: "left",
                    border: `2px solid ${isActive ? "#6366f1" : "var(--border)"}`,
                    background: isActive ? "rgba(99,102,241,.08)" : "var(--card-bg)",
                    fontFamily: "inherit", transition: "all .15s",
                    boxShadow: isActive ? "0 0 0 3px rgba(99,102,241,.2)" : "none",
                  }}
                  onMouseEnter={e => { if (!isActive) { e.currentTarget.style.borderColor = "#6366f1"; e.currentTarget.style.transform = "translateY(-2px)"; } }}
                  onMouseLeave={e => { if (!isActive) { e.currentTarget.style.borderColor = "var(--border)"; e.currentTarget.style.transform = "none"; } }}
                >
                  <div style={{ display: "flex", width: "100%", justifyContent: "space-between", alignItems: "flex-start" }}>
                    <span style={{ fontSize: "1.6rem", lineHeight: 1 }}>{card.emoji}</span>
                    <span style={{ fontSize: ".68rem", fontWeight: 700, padding: "3px 8px", borderRadius: 20, background: dc.bg, color: dc.text, border: `1px solid ${dc.border}` }}>
                      {dc.label}
                    </span>
                  </div>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: ".9rem", marginBottom: 4, color: "var(--text)" }}>{card.topic}</div>
                    <div style={{ fontSize: ".75rem", color: "var(--muted)", lineHeight: 1.4 }}>{card.hint}</div>
                  </div>
                  {isActive && <div style={{ fontSize: ".72rem", fontWeight: 700, color: "#6366f1", marginTop: 2 }}>✦ Viewing explanation →</div>}
                </button>
              );
            })}
          </div>
        </div>

        {/* Explanation panel — sticky on desktop, stacks below cards on mobile */}
        {activeTopic && (
          <div className="exemplar-expl-panel">
            <div className="premium-card" style={{ borderLeft: "4px solid #6366f1" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 14 }}>
                <div>
                  <div style={{ fontSize: "1.5rem", marginBottom: 4 }}>{activeTopic.emoji}</div>
                  <h3 style={{ margin: 0, fontSize: "1rem", color: "var(--text)" }}>{activeTopic.topic}</h3>
                  <div style={{ fontSize: ".72rem", color: "var(--muted)", marginTop: 2 }}>{selectedGrade} · {selectedSubject}</div>
                </div>
                <button onClick={() => { setActiveTopic(null); setExplanation(""); }}
                  style={{ background: "none", border: "none", cursor: "pointer", color: "var(--muted)", fontSize: "1.3rem", lineHeight: 1 }}>×</button>
              </div>

              {!paidAccess ? (
                <UpgradeCard onClose={() => setActiveTopic(null)} onUpgrade={() => setActivePage?.("subscriptionPlans")} />
              ) : loading ? (
                <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 10, padding: "24px 0" }}>
                  <div style={{ width: 32, height: 32, border: "3px solid rgba(99,102,241,.2)", borderTopColor: "#6366f1", borderRadius: "50%", animation: "spin 0.9s linear infinite" }} />
                  <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
                  <p style={{ color: "var(--muted)", fontSize: ".82rem" }}>Loading explanation…</p>
                </div>
              ) : explanation ? (
                <>
                  <div className="markdown-content" style={{ fontSize: ".85rem", maxHeight: 480, overflowY: "auto" }}>
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{explanation}</ReactMarkdown>
                  </div>
                  <div style={{ marginTop: 14, paddingTop: 14, borderTop: "1px solid var(--border)", display: "flex", gap: 8, flexWrap: "wrap" }}>
                    <button
                      onClick={() => generatePractice(activeTopic)}
                      disabled={practiceLoading}
                      style={{ padding: "7px 12px", borderRadius: 8, border: "none", background: "linear-gradient(135deg,#059669,#0891b2)", color: "#fff", fontWeight: 700, fontSize: ".78rem", cursor: "pointer", fontFamily: "inherit" }}>
                      {practiceLoading ? "Generating…" : "🎯 Generate Practice Questions"}
                    </button>
                  </div>

                  {/* ── Inline MCQ practice panel ── */}
                  {practiceLoading && (
                    <div style={{ marginTop: 14, display: "flex", alignItems: "center", gap: 8 }}>
                      <div style={{ width: 18, height: 18, border: "2px solid rgba(16,185,129,.3)", borderTopColor: "#10b981", borderRadius: "50%", animation: "spin 0.9s linear infinite", flexShrink: 0 }} />
                      <span style={{ color: "var(--muted)", fontSize: ".8rem" }}>Generating Exemplar-level practice questions…</span>
                    </div>
                  )}
                  {practiceQs.length > 0 && (
                    <div style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 14 }}>
                      <div style={{ fontSize: ".72rem", fontWeight: 700, color: "#10b981", textTransform: "uppercase", letterSpacing: ".07em" }}>
                        🎯 {practiceQs.length} Practice Questions · {activeTopic.topic}
                      </div>
                      {practiceQs.map((q, qi) => {
                        const selected = practiceAnswers[qi];
                        const revealed = practiceRevealed[qi];
                        return (
                          <div key={qi} style={{ padding: "12px 14px", borderRadius: 10, background: "rgba(16,185,129,.06)", border: "1px solid rgba(16,185,129,.2)" }}>
                            <div style={{ fontWeight: 700, fontSize: ".83rem", marginBottom: 8, color: "var(--text)", lineHeight: 1.4 }}>
                              Q{qi + 1}. {q.q}
                            </div>
                            <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
                              {(q.options || []).map((opt, oi) => {
                                const isCorrect = opt === q.answer;
                                const isSelected = selected === opt;
                                let bg = "transparent", border = "1px solid var(--border)", color = "var(--text)";
                                if (revealed) {
                                  if (isCorrect) { bg = "rgba(16,185,129,.15)"; border = "1px solid #10b981"; color = "#10b981"; }
                                  else if (isSelected && !isCorrect) { bg = "rgba(239,68,68,.1)"; border = "1px solid #ef4444"; color = "#ef4444"; }
                                } else if (isSelected) {
                                  bg = "rgba(99,102,241,.12)"; border = "1px solid #6366f1"; color = "#a5b4fc";
                                }
                                return (
                                  <button key={oi}
                                    onClick={() => { if (!revealed) setPracticeAnswers(p => ({...p, [qi]: opt})); }}
                                    style={{ textAlign: "left", padding: "7px 10px", borderRadius: 7, cursor: revealed ? "default" : "pointer", fontFamily: "inherit", fontSize: ".8rem", background: bg, border, color, transition: "all .12s" }}>
                                    {opt}
                                  </button>
                                );
                              })}
                            </div>
                            {!revealed && selected && (
                              <button
                                onClick={() => setPracticeRevealed(p => ({...p, [qi]: true}))}
                                style={{ marginTop: 8, padding: "5px 12px", borderRadius: 7, border: "none", background: "#10b981", color: "#fff", fontWeight: 700, fontSize: ".76rem", cursor: "pointer", fontFamily: "inherit" }}>
                                Check Answer
                              </button>
                            )}
                            {revealed && (
                              <div style={{ marginTop: 7 }}>
                                <div style={{ fontSize: ".76rem", fontWeight: 700, color: selected === q.answer ? "#10b981" : "#ef4444", marginBottom: 8 }}>
                                  {selected === q.answer ? "✅ Correct!" : `❌ Incorrect — correct: ${q.answer}`}
                                </div>
                                {/* Always show explanation on reveal — for both correct and incorrect answers */}
                                <div style={{ padding: "10px 12px", borderRadius: 8, background: selected === q.answer ? "rgba(16,185,129,.06)" : "rgba(37,99,235,.06)", border: `1px solid ${selected === q.answer ? "rgba(16,185,129,.2)" : "rgba(37,99,235,.2)"}`, fontSize: ".78rem", color: "var(--text)", lineHeight: 1.65 }}>
                                  <strong style={{ color: selected === q.answer ? "#059669" : "#2563eb", display: "block", marginBottom: 4 }}>💡 Explanation</strong>
                                  {q.explanation
                                    ? q.explanation
                                    : `The correct answer is ${q.answer}. Review the concept of ${activeTopic?.topic} and work through this problem step by step to understand why this option is correct.`}
                                </div>
                              </div>
                            )}
                          </div>
                        );
                      })}
                      <button onClick={() => { setPracticeQs([]); setPracticeAnswers({}); setPracticeRevealed({}); }}
                        style={{ alignSelf: "flex-start", padding: "6px 12px", borderRadius: 8, border: "1px solid var(--border)", background: "transparent", color: "var(--muted)", fontSize: ".76rem", cursor: "pointer", fontFamily: "inherit" }}>
                        Clear practice
                      </button>
                    </div>
                  )}
                </>
              ) : null}
            </div>
          </div>
        )}
      </div>

      {/* ── Bottom: tip banner ── */}
      <div style={{ marginTop: 32, padding: "14px 18px", borderRadius: 12, background: "rgba(99,102,241,.06)", border: "1px solid rgba(99,102,241,.2)", display: "flex", gap: 12, alignItems: "flex-start" }}>
        <span style={{ fontSize: "1.4rem", flexShrink: 0 }}>💡</span>
        <div>
          <div style={{ fontWeight: 700, fontSize: ".85rem", marginBottom: 3 }}>How to use this page</div>
          <div style={{ fontSize: ".78rem", color: "var(--muted)", lineHeight: 1.6 }}>
            Click any topic card to get an AI-powered explanation with formula, example, and exam tips. Use the Search bar to research any topic not in the list. Download the Exemplar PDF for practice problems at HOTS (higher-order thinking) level.
          </div>
        </div>
      </div>

    </div>
  );
}
