import { useEffect, useRef, useState } from "react";

const API_BASE = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

const GRADES = ["Grade 5","Grade 6","Grade 7","Grade 8","Grade 9","Grade 10"];
const QUESTION_TYPES = [
  { value: "mcq",        label: "MCQ Only" },
  { value: "subjective", label: "Subjective Only" },
  { value: "mixed",      label: "Mixed (MCQ + Subjective)" },
];
const DIFFICULTIES = ["Easy","Medium","Hard","Mixed"];
const COUNTS = [5,10,15,20,25,30];

/** Print-friendly test paper styles injected into a new window */
const PRINT_STYLES = `
  body { font-family: 'Times New Roman', serif; margin: 40px; color: #000; font-size: 13pt; }
  .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 12px; margin-bottom: 20px; }
  .header h1 { font-size: 16pt; font-weight: 700; margin: 0 0 4px; }
  .header p  { font-size: 11pt; margin: 2px 0; }
  .meta-row { display: flex; justify-content: space-between; font-size: 11pt; border-bottom: 1px solid #ccc; padding-bottom: 8px; margin-bottom: 20px; }
  .section-title { font-size: 13pt; font-weight: 700; margin: 20px 0 12px; border-bottom: 1px solid #aaa; padding-bottom: 4px; }
  .question { margin-bottom: 18px; }
  .question-text { font-weight: 600; margin-bottom: 6px; }
  .options { margin-left: 18px; }
  .option { margin-bottom: 3px; list-style: lower-alpha; }
  .answer-space { border-bottom: 1px dotted #666; height: 22px; margin-bottom: 8px; }
  .marks { float: right; font-size: 10pt; color: #555; }
  @media print { button { display: none; } }
`;

function generatePrintHTML({ schoolName, className, subject, chapter, date, maxMarks, timeLimit, questions }) {
  const mcqs = questions.filter(q => q.type === "mcq");
  const subjs = questions.filter(q => q.type === "subjective");

  const renderMCQ = (q, i) => `
    <div class="question">
      <div class="question-text"><span class="marks">[1 Mark]</span>${i + 1}. ${q.question}</div>
      <ol class="options">
        ${(q.options || []).map(opt => `<li class="option">${opt}</li>`).join("")}
      </ol>
    </div>`;

  const renderSubj = (q, i) => `
    <div class="question">
      <div class="question-text"><span class="marks">[${q.marks || 3} Marks]</span>${i + 1}. ${q.question}</div>
      ${Array.from({ length: q.lines || 4 }).map(() => `<div class="answer-space"></div>`).join("")}
    </div>`;

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Test Paper</title>
    <style>${PRINT_STYLES}</style></head><body>
    <div class="header">
      <h1>${schoolName || "LikhaPoha AI School"}</h1>
      <p>Class: ${className} &nbsp;|&nbsp; Subject: ${subject} &nbsp;|&nbsp; Chapter: ${chapter}</p>
    </div>
    <div class="meta-row">
      <span><strong>Date:</strong> ${date || new Date().toLocaleDateString("en-IN")}</span>
      <span><strong>Time:</strong> ${timeLimit || "1 Hour"}</span>
      <span><strong>Max Marks:</strong> ${maxMarks || questions.reduce((s, q) => s + (q.type === "mcq" ? 1 : (q.marks || 3)), 0)}</span>
    </div>
    <p><strong>Name:</strong> ___________________________________ &nbsp;&nbsp; <strong>Roll No.:</strong> _______</p>
    <p style="font-size:10pt;margin-top:8px;"><em>General Instructions: Read all questions carefully. MCQ section must be answered on OMR sheet if provided. Write answers neatly.</em></p>

    ${mcqs.length > 0 ? `<div class="section-title">Section A — Multiple Choice Questions (1 mark each)</div>${mcqs.map(renderMCQ).join("")}` : ""}
    ${subjs.length > 0 ? `<div class="section-title">Section B — Short / Long Answer Questions</div>${subjs.map(renderSubj).join("")}` : ""}

    <hr style="margin-top:30px;border:1px solid #aaa"/>
    <p style="text-align:center;font-size:10pt;color:#555;margin-top:8px">— End of Test Paper — Generated by LikhaPoha AI</p>
    </body></html>`;
}

function generateAnswerKeyHTML({ schoolName, className, subject, chapter, questions }) {
  const mcqs = questions.filter(q => q.type === "mcq" && q.answer);
  const subjs = questions.filter(q => q.type === "subjective" && q.answer);

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Answer Key</title>
    <style>${PRINT_STYLES}</style></head><body>
    <div class="header">
      <h1>ANSWER KEY — ${schoolName || "LikhaPoha AI School"}</h1>
      <p>${className} | ${subject} | ${chapter}</p>
    </div>
    ${mcqs.length > 0 ? `<div class="section-title">Section A — MCQ Answers</div>
      ${mcqs.map((q, i) => `<p><strong>Q${i+1}.</strong> ${q.answer}</p>`).join("")}` : ""}
    ${subjs.length > 0 ? `<div class="section-title">Section B — Suggested Answers</div>
      ${subjs.map((q, i) => `<div class="question"><div class="question-text">Q${i+1}. ${q.question}</div><p style="color:#1a5276;margin-left:14px">${q.answer}</p></div>`).join("")}` : ""}
    </body></html>`;
}

// ── Daily limit helpers for free-tier teachers ───────────────────────────────
const FREE_TEACHER_DAILY_LIMIT = 2;
function getTeacherDailyKey(username, feature) {
  return `teacher_${feature}_${username}_${new Date().toISOString().slice(0,10)}`;
}
function getTeacherDailyCount(username, feature) {
  try { return parseInt(localStorage.getItem(getTeacherDailyKey(username, feature)) || "0", 10); } catch { return 0; }
}
function incrementTeacherDailyCount(username, feature) {
  try { const k = getTeacherDailyKey(username, feature); localStorage.setItem(k, String(parseInt(localStorage.getItem(k)||"0",10)+1)); } catch { /* non-critical */ }
}
function isTeacherFree(user) {
  return user?.role === "teacher" &&
    (!user?.subscriptionPlan || user.subscriptionPlan === "free") &&
    !user?.accessCbse;
}

export default function TeacherTestPaperPage({ user }) {
  const [syllabus, setSyllabus] = useState({});
  const [syllabusLoading, setSyllabusLoading] = useState(true);

  const [grade, setGrade] = useState("Grade 9");
  const [subject, setSubject] = useState("");
  const [chapter, setChapter] = useState("");
  const [questionType, setQuestionType] = useState("mixed");
  const [difficulty, setDifficulty] = useState("Medium");
  const [count, setCount] = useState(10);
  const [schoolName, setSchoolName] = useState("");
  const [timeLimit, setTimeLimit] = useState("1 Hour");

  const [generating, setGenerating] = useState(false);
  const [questions, setQuestions] = useState([]);
  const [error, setError] = useState("");
  const [previewMode, setPreviewMode] = useState(false);

  // Session history of generated papers
  const [history, setHistory] = useState([]);
  const [historyOpen, setHistoryOpen] = useState(false);

  useEffect(() => {
    async function loadSyllabus() {
      setSyllabusLoading(true);
      try {
        const res = await fetch(`${API_BASE}/api/syllabus`);
        const data = await res.json();
        setSyllabus(data.syllabus || {});
      } catch { /* use empty */ }
      setSyllabusLoading(false);
    }
    loadSyllabus();
  }, []);

  const subjects = Object.keys(syllabus?.[grade]?.CBSE || {});
  const chapters = (syllabus?.[grade]?.CBSE?.[subject] || []).filter(c => c !== "Uploaded Book Content");

  useEffect(() => {
    setSubject(subjects[0] || "");
    setChapter("");
  }, [grade]);

  useEffect(() => {
    setChapter(chapters[0] || "");
  }, [subject, grade]);

  // ── Free-tier daily limit ──────────────────────────────────────────────────
  const freeTeacher = isTeacherFree(user);
  const todayTestCount = freeTeacher ? getTeacherDailyCount(user?.username, "testpaper") : 0;
  const testLimitReached = freeTeacher && todayTestCount >= FREE_TEACHER_DAILY_LIMIT;

  async function handleGenerate() {
    if (testLimitReached) return;
    if (!grade || !subject || !chapter) {
      setError("Please select Grade, Subject and Chapter.");
      return;
    }
    setError("");
    setGenerating(true);
    setQuestions([]);
    setPreviewMode(false);

    try {
      // Calculate MCQ and subjective counts
      let mcqCount = 0, subjCount = 0;
      if (questionType === "mcq")        { mcqCount = count; }
      else if (questionType === "subjective") { subjCount = count; }
      else { mcqCount = Math.ceil(count * 0.6); subjCount = count - mcqCount; }

      const res = await fetch(`${API_BASE}/api/teacher/test-paper/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${user?.accessToken}`,
        },
        body: JSON.stringify({
          grade, subject, chapter, difficulty,
          mcq_count: mcqCount,
          subjective_count: subjCount,
        }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) throw new Error(data.detail || data.message || "Generation failed");
      const qs = data.questions || [];
      setQuestions(qs);
      setPreviewMode(true);
      if (freeTeacher) incrementTeacherDailyCount(user?.username, "testpaper");
      // Save to session history
      setHistory(prev => [{
        grade, subject, chapter, difficulty, questionType, count,
        ts: new Date().toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }),
        date: new Date().toLocaleDateString("en-IN"),
        questions: qs,
      }, ...prev.slice(0, 9)]);
    } catch (err) {
      setError(err.message || "Failed to generate test paper. Please try again.");
    } finally {
      setGenerating(false);
    }
  }

  function handlePrintPaper() {
    const html = generatePrintHTML({
      schoolName, className: grade, subject, chapter,
      date: new Date().toLocaleDateString("en-IN"),
      timeLimit, questions,
    });
    const w = window.open("", "_blank");
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => { w.print(); }, 500);
  }

  function handlePrintAnswerKey() {
    const html = generateAnswerKeyHTML({ schoolName, className: grade, subject, chapter, questions });
    const w = window.open("", "_blank");
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => { w.print(); }, 500);
  }

  const mcqs = questions.filter(q => q.type === "mcq");
  const subjs = questions.filter(q => q.type === "subjective");

  return (
    <div className="premium-page" style={{ maxWidth: 900 }}>
      <div className="premium-header">
        <p className="eyebrow">Teacher Tools</p>
        <h2>📝 Create Test Paper</h2>
        <p>Generate a customised test paper for any grade and chapter. Download the question paper and answer key instantly.</p>
      </div>

      {/* Configuration card */}
      <div className="premium-card" style={{ marginBottom: 24 }}>
        <h3 style={{ marginBottom: 16 }}>⚙️ Paper Settings</h3>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14, marginBottom: 14 }}>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>Grade</span>
            <select value={grade} onChange={e => setGrade(e.target.value)}>
              {GRADES.map(g => <option key={g}>{g}</option>)}
            </select>
          </label>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>Subject</span>
            <select value={subject} onChange={e => setSubject(e.target.value)}>
              {syllabusLoading ? <option>Loading…</option> : subjects.map(s => <option key={s}>{s}</option>)}
            </select>
          </label>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>Chapter</span>
            <select value={chapter} onChange={e => setChapter(e.target.value)}>
              {chapters.length === 0 ? <option>Select subject first</option> : chapters.map(c => <option key={c}>{c}</option>)}
            </select>
          </label>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 14, marginBottom: 14 }}>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>Question Type</span>
            <select value={questionType} onChange={e => setQuestionType(e.target.value)}>
              {QUESTION_TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
            </select>
          </label>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>Difficulty</span>
            <select value={difficulty} onChange={e => setDifficulty(e.target.value)}>
              {DIFFICULTIES.map(d => <option key={d}>{d}</option>)}
            </select>
          </label>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>Total Questions</span>
            <select value={count} onChange={e => setCount(Number(e.target.value))}>
              {COUNTS.map(n => <option key={n}>{n}</option>)}
            </select>
          </label>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, marginBottom: 16 }}>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>School Name <span style={{ fontWeight: 400 }}>(optional)</span></span>
            <input placeholder="Your School Name" value={schoolName} onChange={e => setSchoolName(e.target.value)} />
          </label>
          <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span style={{ fontSize: ".82rem", fontWeight: 600, color: "var(--muted)" }}>Time Limit</span>
            <input placeholder="e.g. 1 Hour 30 Minutes" value={timeLimit} onChange={e => setTimeLimit(e.target.value)} />
          </label>
        </div>

        {error && <div className="error-box" style={{ marginBottom: 12 }}>{error}</div>}

        {/* Daily limit banner for free-tier teachers */}
        {freeTeacher && (
          <div style={{ marginBottom: 10, padding: "8px 12px", borderRadius: 8, fontSize: ".82rem", fontWeight: 600,
            background: testLimitReached ? "rgba(239,68,68,.08)" : "rgba(99,102,241,.07)",
            border: `1px solid ${testLimitReached ? "rgba(239,68,68,.3)" : "rgba(167,139,250,.25)"}`,
            color: testLimitReached ? "#f87171" : "#a78bfa" }}>
            {testLimitReached
              ? `🚫 Daily limit reached (${FREE_TEACHER_DAILY_LIMIT}/${FREE_TEACHER_DAILY_LIMIT} test papers today). Upgrade for unlimited or come back tomorrow.`
              : `📊 ${todayTestCount}/${FREE_TEACHER_DAILY_LIMIT} free test papers used today`}
          </div>
        )}

        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          <button className="primary-btn" onClick={handleGenerate} disabled={generating || syllabusLoading || testLimitReached} style={{ maxWidth: 260 }}>
            {testLimitReached ? "🚫 Daily Limit Reached" : generating ? "⏳ Generating Questions…" : "✨ Generate Test Paper"}
          </button>
          {history.length > 0 && (
            <button onClick={() => setHistoryOpen(h => !h)}
              style={{ padding: "11px 18px", borderRadius: 10, border: "1.5px solid var(--border)", background: "transparent", color: "var(--muted)", fontFamily: "inherit", fontSize: ".85rem", cursor: "pointer" }}>
              🕘 History ({history.length})
            </button>
          )}
        </div>
      </div>

      {/* History panel */}
      {historyOpen && history.length > 0 && (
        <div className="premium-card" style={{ marginBottom: 20 }}>
          <h4 style={{ marginBottom: 12 }}>🕘 Recently Generated Test Papers</h4>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {history.map((h, i) => (
              <button key={i}
                onClick={() => {
                  setQuestions(h.questions);
                  setPreviewMode(true);
                  setGrade(h.grade);
                  setSubject(h.subject);
                  setChapter(h.chapter);
                  setDifficulty(h.difficulty);
                  setHistoryOpen(false);
                }}
                style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 14px", borderRadius: 8, border: "1px solid var(--border)", background: "var(--card-bg)", cursor: "pointer", fontFamily: "inherit", textAlign: "left" }}>
                <div>
                  <span style={{ fontWeight: 700, fontSize: ".85rem" }}>{h.grade} — {h.subject}</span>
                  <span style={{ fontSize: ".75rem", color: "var(--muted)", marginLeft: 8 }}>
                    {h.chapter.length > 40 ? h.chapter.slice(0, 38) + "…" : h.chapter}
                  </span>
                  <div style={{ fontSize: ".72rem", color: "var(--muted)", marginTop: 2 }}>
                    {h.difficulty} · {h.count} questions · {h.questionType}
                  </div>
                </div>
                <div style={{ textAlign: "right", flexShrink: 0 }}>
                  <div style={{ fontSize: ".75rem", color: "var(--muted)" }}>{h.date}</div>
                  <div style={{ fontSize: ".72rem", color: "var(--muted)" }}>{h.ts}</div>
                </div>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Preview */}
      {previewMode && questions.length > 0 && (
        <div>
          {/* Action bar */}
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 20 }}>
            <button className="primary-btn" onClick={handlePrintPaper} style={{ maxWidth: 220 }}>
              🖨️ Download / Print Paper
            </button>
            <button className="secondary-btn" onClick={handlePrintAnswerKey} style={{ maxWidth: 220 }}>
              🔑 Download Answer Key
            </button>
            <button onClick={() => { setPreviewMode(false); setQuestions([]); }}
              style={{ background: "transparent", border: "1px solid var(--border)", borderRadius: 8, padding: "10px 16px", color: "var(--muted)", cursor: "pointer", fontFamily: "inherit", fontSize: ".85rem" }}>
              ← New Paper
            </button>
          </div>

          {/* Summary badges */}
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 16 }}>
            {[
              { label: `${grade} — ${subject}`, color: "#2563eb" },
              { label: chapter.length > 35 ? chapter.slice(0, 35) + "…" : chapter, color: "#7c3aed" },
              { label: `${mcqs.length} MCQs`, color: "#059669" },
              { label: `${subjs.length} Subjective`, color: "#d97706" },
              { label: difficulty, color: "#dc2626" },
              { label: `${questions.reduce((s, q) => s + (q.type === "mcq" ? 1 : (q.marks || 3)), 0)} Marks`, color: "#0891b2" },
            ].map(b => (
              <span key={b.label} style={{ fontSize: ".78rem", fontWeight: 700, padding: "4px 10px", borderRadius: 20, background: `${b.color}22`, color: b.color, border: `1px solid ${b.color}44` }}>
                {b.label}
              </span>
            ))}
          </div>

          {/* MCQ section */}
          {mcqs.length > 0 && (
            <div className="premium-card" style={{ marginBottom: 18 }}>
              <h4 style={{ marginBottom: 14, color: "#2563eb" }}>📌 Section A — Multiple Choice Questions (1 mark each)</h4>
              {mcqs.map((q, i) => (
                <div key={i} style={{ marginBottom: 18, paddingBottom: 14, borderBottom: i < mcqs.length - 1 ? "1px solid var(--border)" : "none" }}>
                  <p style={{ fontWeight: 600, marginBottom: 8 }}>Q{i + 1}. {q.question}</p>
                  <ol style={{ marginLeft: 20, marginBottom: 6 }} type="a">
                    {(q.options || []).map((opt, j) => (
                      <li key={j} style={{ marginBottom: 3, color: opt === q.answer ? "#10b981" : "inherit", fontWeight: opt === q.answer ? 700 : 400 }}>
                        {opt} {opt === q.answer && <span style={{ fontSize: ".75rem", marginLeft: 6, color: "#10b981" }}>✓ Answer</span>}
                      </li>
                    ))}
                  </ol>
                </div>
              ))}
            </div>
          )}

          {/* Subjective section */}
          {subjs.length > 0 && (
            <div className="premium-card">
              <h4 style={{ marginBottom: 14, color: "#7c3aed" }}>📋 Section B — Short / Long Answer Questions</h4>
              {subjs.map((q, i) => (
                <div key={i} style={{ marginBottom: 20, paddingBottom: 16, borderBottom: i < subjs.length - 1 ? "1px solid var(--border)" : "none" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8, marginBottom: 8 }}>
                    <p style={{ fontWeight: 600 }}>Q{i + 1}. {q.question}</p>
                    <span style={{ fontSize: ".75rem", fontWeight: 700, background: "rgba(124,58,237,.15)", color: "#7c3aed", padding: "3px 8px", borderRadius: 6, whiteSpace: "nowrap" }}>
                      [{q.marks || 3} Marks]
                    </span>
                  </div>
                  {q.answer && (
                    <div style={{ background: "rgba(16,185,129,.06)", border: "1px solid rgba(16,185,129,.2)", borderRadius: 8, padding: "10px 12px" }}>
                      <p style={{ fontSize: ".78rem", fontWeight: 700, color: "#10b981", marginBottom: 4 }}>Suggested Answer:</p>
                      <p style={{ fontSize: ".85rem", color: "var(--text-secondary)", lineHeight: 1.6 }}>{q.answer}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
