/**
 * lessonPlanPdf.js
 * Builds a real, selectable-text PDF directly from the lesson-plan markdown
 * returned by /api/teacher/lesson-plan/generate — no browser print dialog,
 * no DOM screenshot. Mirrors the structure/formatting used in
 * progressReportPdf.js (same jsPDF conventions) but parses the simpler
 * markdown shape the lesson_plan_bank handouts are authored in:
 *   ## Section Heading
 *   ### Sub-heading (N minutes)
 *   - bullet
 *   1. numbered item
 *   **bold** inline text
 *   plain paragraphs
 */
import { jsPDF } from "jspdf";

var MARGIN_LEFT = 14;
var MARGIN_RIGHT = 14;
var PAGE_WIDTH = 210; // A4 mm
var CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
var PAGE_BOTTOM = 280;
var LINE_HEIGHT = 5.2;

function ensureSpace(doc, y, needed) {
  if (y + needed > PAGE_BOTTOM) {
    doc.addPage();
    return 20;
  }
  return y;
}

// jsPDF's built-in core fonts (helvetica etc.) only support WinAnsi
// encoding — a single unsupported/unencodable character anywhere in a
// string breaks that whole line's character-width metrics (jsPDF renders
// it with huge extra spacing between every letter, e.g. "F o r   s t u d
// e n t s"). Lesson-plan markdown is authored with plain-language dashes
// and arrows (—, →, ’, “ ”, …) that read fine on screen (React-Markdown
// uses real Unicode fonts) but must be swapped for WinAnsi-safe ASCII
// equivalents before they ever reach jsPDF's text()/splitTextToSize().
var UNICODE_TO_ASCII = [
  [/\u2192/g, "->"],   // →
  [/\u2190/g, "<-"],   // ←
  [/\u2013|\u2014/g, "-"],   // – —
  [/\u2018|\u2019/g, "'"],   // ' '
  [/\u201C|\u201D/g, '"'],   // " "
  [/\u2026/g, "..."],  // …
  [/\u2022/g, "-"],    // •
  [/\u00A0/g, " "],    // non-breaking space
];

function sanitizeForPdf(text) {
  var out = String(text || "");
  for (var i = 0; i < UNICODE_TO_ASCII.length; i++) {
    out = out.replace(UNICODE_TO_ASCII[i][0], UNICODE_TO_ASCII[i][1]);
  }
  // Strip anything else outside printable ASCII / Latin-1 (0x20-0xFF) that
  // could still break WinAnsi metrics, rather than risk corrupting the line.
  out = out.replace(/[^\x20-\x7E\xA0-\xFF]/g, "");
  return out;
}

// Strips markdown bold markers for width-measurement/plain rendering while
// keeping the raw text (jsPDF has no inline rich-text runs without manual
// segment-by-segment font switching, so bold emphasis inside a sentence is
// rendered as plain text — headings/labels still get real bold styling).
function stripInlineMarkdown(text) {
  return sanitizeForPdf(String(text || "").replace(/\*\*(.+?)\*\*/g, "$1"));
}

// Looks ahead from source-line index `fromIndex` (exclusive) for the next
// non-blank markdown line, so a heading's ensureSpace() check can reserve
// room for that first line of content too — otherwise a heading landing
// right at the bottom margin gets orphaned alone on a page while its
// content is pushed to the next page. Every wrapped body line renders at
// the same LINE_HEIGHT regardless of heading/bullet/paragraph type, so one
// constant is sufficient here; this still returns LINE_HEIGHT if there's
// no more content (e.g. the very last heading in the document), which is
// harmless — it just reserves one extra line's worth of room that goes
// unused rather than skipping the check.
function nextContentLineHeight(lines, fromIndex) {
  for (var j = fromIndex + 1; j < lines.length; j++) {
    if (lines[j].trim()) return LINE_HEIGHT;
  }
  return LINE_HEIGHT;
}

function writeWrapped(doc, text, x, y, opts) {
  opts = opts || {};
  var maxWidth = opts.maxWidth || CONTENT_WIDTH - (x - MARGIN_LEFT);
  var lines = doc.splitTextToSize(stripInlineMarkdown(text), maxWidth);
  for (var i = 0; i < lines.length; i++) {
    y = ensureSpace(doc, y, LINE_HEIGHT);
    doc.text(lines[i], x, y);
    y += LINE_HEIGHT;
  }
  return y;
}

export function buildLessonPlanFileName(chapter) {
  var safe = String(chapter || "Lesson_Plan")
    .replace(/[^a-z0-9]+/gi, "_")
    .replace(/^_+|_+$/g, "");
  return "LessonPlan_" + (safe || "Lesson_Plan") + ".pdf";
}

/**
 * @param {string} markdown - raw lesson plan markdown
 * @param {{grade:string, subject:string, chapter:string}} meta
 * @returns {string} filename that was saved
 */
export function generateLessonPlanPdf(markdown, meta) {
  if (!markdown) return null;
  meta = meta || {};

  var doc = new jsPDF();
  var y = 18;

  // ── Header ────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("CBSE Lesson Plan", MARGIN_LEFT, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(70);
  var subtitle = sanitizeForPdf([meta.grade, meta.subject, meta.chapter].filter(Boolean).join("  -  "));
  y = writeWrapped(doc, subtitle, MARGIN_LEFT, y);
  doc.setFontSize(9);
  doc.text("Generated by Likha Poha AI for Teacher - " + new Date().toLocaleDateString("en-IN"), MARGIN_LEFT, y);
  doc.setTextColor(0);
  y += 4;
  doc.setDrawColor(180);
  doc.line(MARGIN_LEFT, y, PAGE_WIDTH - MARGIN_RIGHT, y);
  y += 8;

  // ── Body: line-by-line markdown parse ──────────────────────────────────
  var lines = String(markdown).split(/\r?\n/);

  for (var i = 0; i < lines.length; i++) {
    var raw = lines[i];
    var line = raw.trim();
    if (!line) { y += 2; continue; }

    var h2 = line.match(/^##\s+(.+)$/);
    var h3 = line.match(/^###\s+(.+)$/);
    var bullet = line.match(/^[-*]\s+(.+)$/);
    var numbered = line.match(/^(\d+)\.\s+(.+)$/);

    if (h2) {
      // Reserve room for the heading itself PLUS at least one line of the
      // content that follows it — otherwise a heading landing right at the
      // bottom margin gets orphaned alone on a page while its first bullet/
      // paragraph is pushed to the next page (a heading with no visible
      // content under it looks broken). nextContentLineHeight() confirms
      // there IS a next line, so the heading and its first line of content
      // page-break together.
      y = ensureSpace(doc, y, 12 + nextContentLineHeight(lines, i));
      y += 3;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(30, 41, 59);
      y = writeWrapped(doc, h2[1], MARGIN_LEFT, y);
      doc.setDrawColor(210);
      doc.line(MARGIN_LEFT, y - 3, PAGE_WIDTH - MARGIN_RIGHT, y - 3);
      doc.setTextColor(0);
      y += 2;
      continue;
    }

    if (h3) {
      y = ensureSpace(doc, y, 9 + nextContentLineHeight(lines, i));
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(51, 65, 85);
      y = writeWrapped(doc, h3[1], MARGIN_LEFT, y);
      doc.setTextColor(0);
      continue;
    }

    if (bullet) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      y = ensureSpace(doc, y, LINE_HEIGHT);
      var lines1 = doc.splitTextToSize(stripInlineMarkdown(bullet[1]), CONTENT_WIDTH - 6);
      for (var b = 0; b < lines1.length; b++) {
        y = ensureSpace(doc, y, LINE_HEIGHT);
        doc.text(b === 0 ? "\u2022" : " ", MARGIN_LEFT, y);
        doc.text(lines1[b], MARGIN_LEFT + 5, y);
        y += LINE_HEIGHT;
      }
      continue;
    }

    if (numbered) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      var prefix = numbered[1] + ".";
      var lines2 = doc.splitTextToSize(stripInlineMarkdown(numbered[2]), CONTENT_WIDTH - 8);
      for (var n = 0; n < lines2.length; n++) {
        y = ensureSpace(doc, y, LINE_HEIGHT);
        if (n === 0) doc.text(prefix, MARGIN_LEFT, y);
        doc.text(lines2[n], MARGIN_LEFT + 7, y);
        y += LINE_HEIGHT;
      }
      continue;
    }

    // Plain paragraph line
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y = writeWrapped(doc, line, MARGIN_LEFT, y);
  }

  // ── Footer on every page ────────────────────────────────────────────────
  var pageCount = doc.internal.getNumberOfPages();
  for (var p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(
      "Likha Poha AI Lesson Plan - For classroom use only",
      PAGE_WIDTH / 2,
      292,
      { align: "center" }
    );
    doc.setTextColor(0);
  }

  var filename = buildLessonPlanFileName(meta.chapter);
  doc.save(filename);
  return filename;
}
