import {
    BarChart3,
    BookOpen,
    Brain,
    Calculator,
    ClipboardList,
    CreditCard,
    HelpCircle,
    Home,
    KeyRound,
    Megaphone,
    MonitorPlay,
    Tags,
    GraduationCap,
    Handshake,
    Trophy,
    UploadCloud,
    Video,
  } from "lucide-react";
  
  export const PAGE_ICONS = {
    dashboard: Home,
    lessons: BookOpen,
    doubt: HelpCircle,
    quiz: Brain,
    mockTest: ClipboardList,
    resources: Video,
    analytics: BarChart3,
    leaderboard: Trophy,
    ragUpload: UploadCloud,
    subscriptionSettings: Tags,
    pricingCalculator: Calculator,
    salesIncentives: Handshake,
    salesDemo: MonitorPlay,
    salesCollaterals: Megaphone,
    subscriptionPlans: CreditCard,
    teacherDashboard: GraduationCap,
    changePassword: KeyRound,
  };
