export const EXAMS=[{key:"jee_main",label:"JEE Main",color:"#6366f1"},{key:"neet_ug",label:"NEET UG",color:"#10b981"},{key:"cuet_ug",label:"CUET UG",color:"#f59e0b"},{key:"sat",label:"SAT",color:"#3b82f6"},{key:"ielts",label:"IELTS",color:"#8b5cf6"},{key:"toefl_ibt",label:"TOEFL",color:"#06b6d4"}];
export const SC:Record<string,string>={Physics:"#6366f1",Chemistry:"#10b981",Mathematics:"#f59e0b",Biology:"#22c55e",English:"#8b5cf6","General Test":"#f97316",Listening:"#ec4899",Reading:"#06b6d4","Reading & Writing":"#6366f1","Integrated Skills":"#10b981","Vocabulary & Grammar":"#a78bfa"};
export interface RS{formulas:{expr:string;desc:string}[];traps:string[];mnemonics:string[];}
export const QR:Record<string,Record<string,RS>>={
  jee_main:{
    Physics:{formulas:[{expr:"v=u+at · s=ut+½at² · v²=u²+2as",desc:"SUVAT"},{expr:"F=ma · W=mg (g=10 JEE)",desc:"Newton"},{expr:"V=IR · P=I²R=V²/R",desc:"Ohm's"},{expr:"E=hf=hc/λ · KE_max=hf−φ",desc:"Photoelectric"},{expr:"n₁sinθ₁=n₂sinθ₂ · 1/f=1/v+1/u",desc:"Snell/Optics"}],traps:["a is NEGATIVE for deceleration — fix sign convention first.","At projectile max height: v_y=0 but v_x unchanged.","SHM: a=−ω²x (towards mean, not away from it).","Lenz law: opposes CHANGE in flux, not the flux itself.","Escape velocity is independent of object mass."],mnemonics:["SUVAT: S=disp · U=init · V=final · A=accel · T=time","CAST: All+ in Q1 · Sin+ in Q2 · Tan+ in Q3 · Cos+ in Q4"]},
    Chemistry:{formulas:[{expr:"n=m/M · N=n×Nₐ (Nₐ=6.022×10²³)",desc:"Mole"},{expr:"PV=nRT (R=8.314 J/mol·K)",desc:"Ideal Gas"},{expr:"ΔG=ΔH−TΔS · ΔG°=−RT lnK",desc:"Gibbs"},{expr:"pH=−log[H⁺] · pH+pOH=14",desc:"Acid-Base"},{expr:"t½=0.693/k (1st order)",desc:"Kinetics"}],traps:["Rate order from EXPERIMENT only — never from stoichiometry.","Kp=Kc ONLY when Δn=0 (equal moles of gas on both sides).","SN2=inversion (Walden) · SN1=racemic (via carbocation)."],mnemonics:["OIL RIG: Oxidation Is Loss · Reduction Is Gain","Electronegativity order: F > O > N > Cl > Br"]},
    Mathematics:{formulas:[{expr:"sin²θ+cos²θ=1 · 1+tan²θ=sec²θ",desc:"Trig identities"},{expr:"x=(−b±√D)/2a · D=b²−4ac",desc:"Quadratic"},{expr:"d/dx(sinx)=cosx · d/dx(eˣ)=eˣ",desc:"Derivatives"},{expr:"∫₀^a f(x)dx=∫₀^a f(a−x)dx",desc:"King's Property (very frequent!)"},{expr:"nCr=n!/r!(n−r)! · sum GP: S=a(rⁿ−1)/(r−1)",desc:"Combinatorics/GP"}],traps:["ILATE for integration by parts: Inv>Log>Algebraic>Trig>Exp.","Definite integral ≠ geometric area if f(x)<0 — use |f(x)|.","log(a+b) ≠ log a + log b. Only log(ab) = log a + log b.","Absolute value: |x−3|=5 gives x=8 AND x=−2."],mnemonics:["ILATE: Inverse Trig > Log > Algebraic > Trig > Exponential","SOH CAH TOA: Sin=O/H · Cos=A/H · Tan=O/A"]},
  },
  neet_ug:{
    Biology:{formulas:[{expr:"6CO₂+6H₂O+light→C₆H₁₂O₆+6O₂",desc:"Photosynthesis"},{expr:"PS-II=680nm · PS-I=700nm · Z-scheme",desc:"Photosystems"},{expr:"p²+2pq+q²=1 · p+q=1",desc:"Hardy-Weinberg"},{expr:"~38 ATP per glucose (aerobic respiration)",desc:"Cellular ATP yield"}],traps:["Glycolysis occurs in CYTOPLASM — NOT mitochondria.","Krebs cycle: mitochondrial MATRIX · ETC: inner MEMBRANE.","C4 plants: OAA formed in MESOPHYLL → Calvin in BUNDLE SHEATH.","Mitosis→2 DIPLOID cells · Meiosis→4 HAPLOID cells.","Apical meristem = length · Lateral meristem = girth (width)."],mnemonics:["PMAT: Prophase · Metaphase · Anaphase · Telophase (cell division)","KPCOFGS: Kingdom→Phylum→Class→Order→Family→Genus→Species"]},
    Physics:{formulas:[{expr:"v=u+at · s=ut+½at²",desc:"Kinematics"},{expr:"V=IR · P=I²R",desc:"Ohm's law"},{expr:"1/f=1/v+1/u",desc:"Mirror/Lens formula"}],traps:["NEET Physics is 100% from NCERT Class 11 & 12 — no extra concepts.","Lenz law: induced current OPPOSES change in flux (not flux itself)."],mnemonics:["SUVAT covers all 1D and projectile motion"]},
    Chemistry:{formulas:[{expr:"n=m/M · N=n×Nₐ",desc:"Mole concept"},{expr:"pH=−log[H⁺] · pH+pOH=14",desc:"Acid-Base"},{expr:"sp=linear · sp²=trigonal planar · sp³=tetrahedral",desc:"Hybridisation"}],traps:["NEET Chemistry: ~85% questions come directly from NCERT text.","Aromatic: must be PLANAR + CYCLIC + 4n+2 π electrons (Hückel)."],mnemonics:["OIL RIG: Oxidation Is Loss · Reduction Is Gain"]},
  },
  cuet_ug:{
    English:{formulas:[{expr:"Active→Passive: Obj+be+V3+by+Subj",desc:"Voice change rule"},{expr:"Type 1 conditional: If+present simple, will+base verb",desc:"Real/possible future"},{expr:"Direct→Indirect: change pronouns + backshift tense",desc:"Reported speech"}],traps:["Its (possessive pronoun) vs It's (it is) — extremely common CUET trap.","Fewer is for COUNTABLE nouns · Less is for UNCOUNTABLE nouns.","Affect (verb) vs Effect (noun): 'The cold affected him.' vs 'The effect was mild.'"],mnemonics:["FANBOYS: For·And·Nor·But·Or·Yet·So (coordinating conjunctions)","BEING: the auxiliary forms of 'be' (is/am/are/was/were/be/been/being)"]},
    "General Test":{formulas:[{expr:"SI=PRT/100 · CI=P(1+R/100)^T−P",desc:"Simple & Compound Interest"},{expr:"Speed=Distance/Time · Average speed=2s₁s₂/(s₁+s₂)",desc:"Speed-Distance-Time"},{expr:"Profit%=(Profit/CP)×100",desc:"Profit/Loss always on Cost Price"}],traps:["Average speed ≠ (s1+s2)/2 — use harmonic formula for equal distances.","LCM × HCF = Product of the two numbers (valid for TWO numbers only).","Compound interest: if half-yearly → halve the rate AND double the time."],mnemonics:["BODMAS: Brackets·Of·Division·Multiplication·Addition·Subtraction"]},
  },
  sat:{
    "Reading & Writing":{formulas:[{expr:"SVO: Subject + Verb + Object (base sentence)",desc:"Always check subject-verb agreement first"},{expr:"Parallel: A, B, and C must all match grammatical form",desc:"Lists must be parallel"},{expr:"Active→Passive: Object + be(tense) + V3 + by + Subject",desc:"Voice conversion"}],traps:["Vocabulary in context: choose word that fits PASSAGE meaning, not dictionary.","Its (possessive) vs It's (it is) — SAT's most common trap.","'Fewer' for countable · 'Less' for uncountable.","Transition words: but/however=contrast · therefore/thus=result."],mnemonics:["MICE: Main idea · Inference · Context vocab · Evidence (4 core R&W types)","FANBOYS: For And Nor But Or Yet So (coordinating conjunctions)"]},
    Mathematics:{formulas:[{expr:"y=mx+b · slope=(y₂−y₁)/(x₂−x₁)",desc:"Linear equations (~35% of SAT Math)"},{expr:"x=(−b±√(b²−4ac))/2a · vertex: (−b/2a, f(−b/2a))",desc:"Quadratic"},{expr:"Prob=favourable/total · P(A or B)=P(A)+P(B)−P(A and B)",desc:"Probability"},{expr:"Area circle=πr² · C=2πr",desc:"Circle geometry"}],traps:["x²=9 → x=±3 (not just +3) — square root has TWO solutions.","'X% more than Y' = Y×(1+X/100), NOT Y+X.","Average trap: if avg of n numbers is A, the SUM is n×A.","Use Desmos graphing calculator built into Digital SAT for all graph questions."],mnemonics:["SOHCAHTOA: Sin=O/H · Cos=A/H · Tan=O/A","PEMDAS: Parentheses · Exponents · Mult/Div · Add/Sub"]},
  },
  ielts:{
    Listening:{formulas:[{expr:"Gap-fill: write EXACT words from recording (follow word limit)",desc:"Spelling must be correct"},{expr:"MCQ: read all options BEFORE audio plays",desc:"Pre-reading maximises comprehension"}],traps:["Distractors: speaker often says wrong answer first, then corrects. WAIT for final answer.","Word limit: writing 3 words when limit is 'NO MORE THAN 2 WORDS' = WRONG.","Spelling error in gap-fill = wrong answer (British OR American accepted, but must be correct).","Negatives trap: 'lecture is NOT on Tuesday' — students write 'Tuesday' because they heard it."],mnemonics:["CUPS: Copy (key words) · Underline · Predict word type · Scan next question during pauses","4 recordings: Social/everyday → Social/training → Monologue → Academic lecture"]},
    Reading:{formulas:[{expr:"T/F/NG: True=passage agrees · False=contradicts · NG=not mentioned",desc:"Most important distinction"},{expr:"Skim (main idea) → Scan (specific detail) → Answer",desc:"Time-efficient sequence"}],traps:["NOT GIVEN ≠ FALSE. If the passage simply doesn't mention it → Not Given.","Matching Headings: must reflect MAIN IDEA of paragraph — never a detail or example.","Paraphrase: the correct answer almost always uses DIFFERENT words from the passage.","Time limit: 60 minutes, no transfer time. Spend max 20 minutes per passage."],mnemonics:["TFNG: Text Firmly Nods=True · Negates=False · Goes nowhere=Not Given","SKIM→SCAN→SOLVE (reading strategy for each passage)"]},
    "Vocabulary & Grammar":{formulas:[{expr:"CALF: Cohesion · Accuracy · Lexis · Fluency (4 IELTS writing/speaking criteria)",desc:"What examiners grade"},{expr:"PEEL paragraph: Point → Evidence → Explain → Link back",desc:"Writing Task 2 structure"}],traps:["Collocation: 'make a mistake' NOT 'do a mistake' · 'do homework' NOT 'make homework'.","Prepositions: 'interested IN' NOT 'interested ON' · 'depend ON' NOT 'depend OF'.","Tense consistency: once you set the tense, don't switch without reason."],mnemonics:["PEEL: Point · Evidence · Explain · Link (Task 2 paragraph structure)","Discourse markers: furthermore=addition · however=contrast · therefore=result"]},
  },
  toefl_ibt:{
    Reading:{formulas:[{expr:"Prose Summary: choose 3 of 6 (main ideas only, not details)",desc:"Most common mistake"}],traps:["Inference: must be STRONGLY implied — not just plausible.","Sentence insertion: watch for pronouns like 'this' or 'these'."],mnemonics:["FLIP: Factual · Logic/inference · Idea (main) · Purpose"]},
    Listening:{formulas:[{expr:"NOTE: Note key terms · Organize · Track transitions · Extract main idea",desc:"Note-taking strategy"}],traps:["Gist/purpose: most GENERAL accurate description.","Function questions: WHY the professor says it, not what it is."],mnemonics:["LAPS: Label (topic) · Attitude · Purpose · Support (evidence)"]},
    "Integrated Skills":{formulas:[{expr:"Integrated Writing: 150-225 words · 20 min · LECTURE vs Reading",desc:"Summarise lecture, not your opinion"},{expr:"Academic Discussion: 100+ words · 10 min · Add NEW point",desc:"Don't just agree with classmates"}],traps:["Integrated Writing: summarise LECTURE challenges to reading — do NOT give your own opinion.","Academic Discussion: add a SPECIFIC reason or example — generic statements score low."],mnemonics:["IDEAL: Intro · Describe (reading) · Explain (lecture) · Amplify · Link","3C: Claim · Concrete example · Connect to classmate or question"]},
  },
};
